### ISSUE TITLE
谱面下载添加一次性 token 验证和日限额

### ISSUE THREAD

**Issue by JoinChang** [Lost-MSth/Arcaea-server#1]
为了防止被恶意刷下载流量，希望下载链接能添加一次性 token 验证和日限额。

**Comment by Lost-MSth** [comment]
OK.
下次更新会加上的（咕咕咕
一次性token，为了防止下载出错，会用限时token的
日限额是要干什么，emm，下载资源的日限额吗，不太清楚这会不会影响正常下载（不太清楚你干啥有这么大的流量），我加上试试吧

**Comment by JoinChang** [comment]
因为arc也是有日限额这种东西的，下载过多会被限制，具体多少我也不清楚，但下完一次全曲应该是有的（
