### ISSUE TITLE
ios端无法登入

### ISSUE THREAD

**Issue by fhy-naive** [Lost-MSth/Arcaea-server#10]
注册时ios端显示失败，但服务端是接收到数据并且处理成功
![image](https://user-images.githubusercontent.com/47323697/103171272-ebde5980-4885-11eb-8873-5b525116d888.png)
登陆时亦是ios端显示失败，但服务端显示成功
![image](https://user-images.githubusercontent.com/47323697/103171359-9a829a00-4886-11eb-8e43-4ba871059407.png)
对比官服的response大致没有差别，有时json的key顺序会不同（可用有序字典解决），保持顺序仍无法登陆
服务端 win8，python 3.9
ios端 ios13.5.1

**Comment by Lost-MSth** [comment]
啊这，怎么看都像是成功了（）
emm能看一下登录成功后的第一个包的显示是什么吗（aggregate那个），我怀疑是那里返回的错误

**Comment by fhy-naive** [comment]
大部分登录时候是没有aggregate包的，包内是角色数值相关，几十kb，应该是正常的吧？但无论有没有aggregate回复，iOS上都显示无法连接到服务器（悲



---原始邮件---
发件人: "Lost-MSth"<notifications@github.com&gt;
发送时间: 2020年12月27日(周日) 晚上9:20
收件人: "Lost-MSth/Arcaea-server"<Arcaea-server@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"fhy-naive"<1369188290@qq.com&gt;;
主题: Re: [Lost-MSth/Arcaea-server] ios端无法登入 (#10)




 
啊这，怎么看都像是成功了（）
 emm能看一下登录成功后的第一个包的显示是什么吗（aggregate那个），我怀疑是那里返回的错误

**Comment by Lost-MSth** [comment]
有东西返回就没啥事，但登录的时候一定有aggregate的，那里面是用户数据，地图数据，购买数据，系统参数之类的，不过我现在觉得问题不在这里
返回的success不可能出现无法连接服务器啊，发包回包正常 证书也大概没问题（好像也不一定），这是什么奇葩bug（大概率是ios问题，服务器这样看来没啥问题）
确认一下arcaea的版本是3.4.0

我没有ios设备，不太好测试啊（我这就去求设备）

**Comment by fhy-naive** [comment]
谢谢，有劳你费心了



---原始邮件---
发件人: "Lost-MSth"<notifications@github.com&gt;
发送时间: 2020年12月27日(周日) 晚上9:38
收件人: "Lost-MSth/Arcaea-server"<Arcaea-server@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"fhy-naive"<1369188290@qq.com&gt;;
主题: Re: [Lost-MSth/Arcaea-server] ios端无法登入 (#10)




 
有东西返回就没啥事，但登录的时候一定有aggregate的，那里面是用户数据，地图数据，购买数据，系统参数之类的，不过我现在觉得问题不在这里
 返回的success不可能出现无法连接服务器啊，发包回包正常 证书也大概没问题（好像也不一定），这是什么奇葩bug（大概率是ios问题，服务器这样看来没啥问题）
 确认一下arcaea的版本是3.4.0
 
我没有ios设备，不太好测试啊（我这就去求设备）

**Comment by fhy-naive** [comment]
不好意思再打扰一下，似乎本地服务器login时几乎不出现aggregate返回（又重试了数十次）

对比官服


login返回的json文件在key的顺序上有所不同，这也许会影响ios判断登陆情况？给字典r（main函数93行左右）加上OrderedDict似乎无效，jsonify()函数好像不存储顺序？使用json.dumps()可保留顺序，但在return类型上有偏差（dumps()返回text类型，jsonify()返回application/json类型）

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lost-MSth/Arcaea-server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 晚上9:38
收件人:&nbsp;"Lost-MSth/Arcaea-server"<Arcaea-server@noreply.github.com&gt;;
抄送:&nbsp;"付恒宇"<1369188290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lost-MSth/Arcaea-server] ios端无法登入 (#10)





 
有东西返回就没啥事，但登录的时候一定有aggregate的，那里面是用户数据，地图数据，购买数据，系统参数之类的，不过我现在觉得问题不在这里
 返回的success不可能出现无法连接服务器啊，发包回包正常 证书也大概没问题（好像也不一定），这是什么奇葩bug（大概率是ios问题，服务器这样看来没啥问题）
 确认一下arcaea的版本是3.4.0
 
我没有ios设备，不太好测试啊（我这就去求设备）

**Comment by Lost-MSth** [comment]
key顺序不会影响，字典是无序的 ）

**Comment by Lost-MSth** [comment]
一般来说（实际上还是有个遍历顺序的但是arcaea是直接提数据，所以顺序没关系）

**Comment by fhy-naive** [comment]
emm，但感觉只有可能是在ios端接收数据或服务端传回数据时出锅了。ios端或许可以用一些app进行抓包重定向（Httpcatcher，Thor等），毕竟ios http代理不太稳，我之前用ios局域网http 代理做一些抓包工作时遇到过掉包，阻断的情况。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lost-MSth"<notifications@github.com&gt;; 
发送时间: 2020年12月27日(星期天) 晚上10:18
收件人: "Lost-MSth/Arcaea-server"<Arcaea-server@noreply.github.com&gt;; 
抄送: "付恒宇"<1369188290@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] ios端无法登入 (#10)





 
一般来说（实际上还是有个遍历顺序的但是arcaea是直接提数据，所以顺序没关系）

**Comment by Lost-MSth** [comment]
啊，会这样吗
安卓倒是会在连不通的情况下直连官服，可你这个服务器无法连接就很迷（）

**Comment by Lost-MSth** [comment]
请dalao试了一下，用Charles4.6.1(破解版)成功登了，ios 14.2（18B92)
中途遇到的问题主要是证书认证，ios10以上要在 关于本机 中的 证书信任设置 中完全信任Charles的证书
对了还有win端的证书要丢在受信任中

不知道你有没有成功，希望能帮到

**Comment by fhy-naive** [comment]
感谢回复，换了一台ios设备，重新安装了arc(换成了国际服)，证书设置好便登上了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lost-MSth/Arcaea-server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨2:16
收件人:&nbsp;"Lost-MSth/Arcaea-server"<Arcaea-server@noreply.github.com&gt;;
抄送:&nbsp;"fhy"<1369188290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lost-MSth/Arcaea-server] ios端无法登入 (#10)





 
请dalao试了一下，用Charles4.6.1(破解版)成功登了，ios 14.2（18B92)
 中途遇到的问题主要是证书认证，ios10以上要在 关于本机 中的 证书信任设置 中完全信任Charles的证书
 对了还有win端的证书要丢在受信任中
 
不知道你有没有成功，希望能帮到
