### ISSUE TITLE
光 & 对立（Reunion） 表现不一致

### ISSUE THREAD

**Issue by Young-Lord** [Lost-MSth/Arcaea-server#100]
官方：获得时就是20级觉醒形态，可以进一步升到30级
Arcaea-server：由于没有设置觉醒所需要的核心种类及数量，被server认为没有觉醒形态，最高也只有20级
https://wiki.arcaea.cn/光_&_对立（Reunion）

**Comment by Lost-MSth** [comment]
糟，上次更新懒得手动写觉醒搭档导致的，忘了5没有觉醒核心（）

不过获得时就是20级觉醒这点……有点难办，按理说5的获得是自动的……我在考虑要不要给它人为添加个核心
