### ISSUE TITLE
Axiom of the End issue

### ISSUE THREAD

**Issue by PgMiku** [Lost-MSth/Arcaea-server#101]
Hi. I have an issue when playing Axiom of the End:
![photo_2023-03-31_21-10-18](https://user-images.githubusercontent.com/83493897/229144361-5cffb380-40f6-4f47-9bc8-4b1b46e1b10e.jpg)
When I played a Light slide song, the HP bar doesn't reduce 25% of HP. I have tried more than 3 times but it's same as before.
Can you fix it in next version of server? Hope you reply soon. 
Thanks.

Using server: v2.11.1

**Comment by Lost-MSth** [comment]
Are you sure you used the character **Hikari** (or other hikaris) to clear a Light side song?

Anyway, it has nothing to do with the server.

**Comment by PgMiku** [comment]
100% sure. I have tried more than 3 times.

But it still sucks at HP bar.
I

**Comment by Lost-MSth** [comment]
> Anyway, it has nothing to do with the server.

As I said before, the finale challenge is mostly controlled by the client but nor the server.

However, I still tried to help you. After attempt, I just want to @ **Lowiro** now! (OK. Limited to language, I don't know how to express my strong emotions.)

What a fucking bug!!!

After client version 4.4, you cannot decrease the second finale health bar in any other languages, except in English!

**Comment by PgMiku** [comment]
Uh... Okay. 

Thanks for your infomation. I think my database in that account is issue, I'll try to fix it.

And please don't use any sensitive words, I really don't like it...

I'll close this issue now.
