### ISSUE TITLE
Arcaea 4.4.2c Error

### ISSUE THREAD

**Issue by innocentvoice** [Lost-MSth/Arcaea-server#102]
**Describe the bug 问题描述**
近期在与 Arcaea 4.4.2c 版本进行配合时，似乎出现了“SAVE_FULL_UNLOCK ”功能失灵的情况。同时，对于官方歌曲的 ptt 计算也未能正常工作。

**To Reproduce 复现过程**
1. Go to 'setting.py', change SAVE_FULL_UNLOCK = False to SAVE_FULL_UNLOCK = True
2. Restart the server
3. Login to Arcaea
4. Click on cloud sync and not unlocked.

**Error log 报错日志**

```
no error logs
```

**Screenshots 截图**

**Environment 环境**
 - Server OS: Ubuntu Server 22.04
 - Client OS: MIUI 13, Android 12
 - Server Version: 2.11.1
 - Client Version: 4.4.2c
 - Others like python version, flask version, some proxy softwares if you used... : None

**Additional context 附加内容**
服务器更新什么时候发布呢？

**Comment by A-random-githuber** [comment]
I got the same problem as well

**Comment by Lost-MSth** [comment]
本来想问问具体问题的，结果我发现了一个不得不问的细节

那个，您确定您的设置文件文件名是 `setting.py` 吗

顺便问一下其它的，存档解锁失灵指的是哪部分出现问题，“官方歌曲的 ptt 计算”出现了什么问题？

**Comment by innocentvoice** [comment]
> 那个，您确定您的设置文件文件名是 `setting.py` 吗

是的
> 顺便问一下其它的，存档解锁失灵指的是哪部分出现问题，“官方歌曲的 ptt 计算”出现了什么问题？

当我完成一首歌曲时，ptt仍然停留在“keep”状态。

**Comment by Lost-MSth** [comment]
嘶……讲道理是我的问题，没怎么考虑过了好久跨一堆版本升级的用户怎么在他们不想重看文档的情况下给他们用法改变的提示……

v2.10.1 开始，配置文件变成了 `config.py`，允许部分设置，缺少的部分按照默认值

v2.9.0 开始，不提供官方歌曲定数数据，可以用 `tools` 里面[脚本](https://github.com/Lost-MSth/Arcaea-server/blob/master/tools/update_song.py)来导入[数据](https://github.com/Arcaea-Infinity/ArcaeaSongDatabase)

**Comment by innocentvoice** [comment]
> 嘶……讲道理是我的问题，没怎么考虑过了好久跨一堆版本升级的用户怎么在他们不想重看文档的情况下给他们用法改变的提示……
> 
> v2.10.1 开始，配置文件变成了 `config.py`，允许部分设置，缺少的部分按照默认值
> 
> v2.9.0 开始，不提供官方歌曲定数数据，可以用 `tools` 里面[脚本](https://github.com/Lost-MSth/Arcaea-server/blob/master/tools/update_song.py)来导入[数据](https://github.com/Arcaea-Infinity/ArcaeaSongDatabase)

非常感谢您帮助我！
