### ISSUE TITLE
INFO in _internal: 127.0.0.1 - - [12/Apr/2023 04:40:42] "POST /latte/13/user/ HTTP/1.1" 200 -

### ISSUE THREAD

**Issue by enchanteddaemon** [Lost-MSth/Arcaea-server#103]
omg bro

![Screenshot_2023-04-12-04-39-48-50_d5d752306f588094c2ac66b8acd5b66a.jpg](https://user-images.githubusercontent.com/100534753/231271907-ca93214c-1918-45aa-9035-b7879ba38d1a.jpg)

![Screenshot_2023-04-12-04-41-15-61_d5d752306f588094c2ac66b8acd5b66a.jpg](https://user-images.githubusercontent.com/100534753/231271904-b4a85c31-210e-4fd6-804b-0d2aa082eb3c.jpg)

![Screenshot_2023-04-12-04-40-07-50_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/100534753/231271905-637bea94-1492-45d8-a1f8-ffb730d2e322.jpg)

![Screenshot_2023-04-12-04-41-31-93_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/100534753/231271906-56ea9922-4a12-497a-a992-a6fdcb2a927f.jpg)

**Comment by Lost-MSth** [comment]
More details please. Client and server version.

It seems to be no problem. You can try to print the return message to check the reason.

**Comment by enchanteddaemon** [comment]
> More details please. Client and server version.
> 
> It seems to be no problem. You can try to print the return message to check the reason.

Arcaea client version 3.5.3c/3.5.3
Arcaea server version 2.7.0

**Comment by Lost-MSth** [comment]
After line 205 in `main.py`, print the `token` and the `error_code` to see what happened. Same for line 233.

**Comment by enchanteddaemon** [comment]
> After line 205 in `main.py`, print the `token` and the `error_code` to see what happened. Same for line 233.

how to do it?

**Comment by Lost-MSth** [comment]
Well... I think you should learn something about Python. 
https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming

**Comment by enchanteddaemon** [comment]
> Well... I think you should learn something about Python. 
> https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming

?

![Screenshot_2023-04-12-21-33-53-97_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://user-images.githubusercontent.com/100534753/231458640-3bb0ff87-d227-493b-91ab-68f3f948ac6b.jpg)

![Screenshot_2023-04-12-21-33-42-87_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://user-images.githubusercontent.com/100534753/231458639-c66771c1-b535-4bf4-9572-045dc250fe99.jpg)

**Comment by enchanteddaemon** [comment]
Marking closed cuz i fixed it (with my friend)

**Comment by enchanteddaemon** [comment]
![Screenshot_2023-04-12-22-30-24-49_d5d752306f588094c2ac66b8acd5b66a.jpg](https://user-images.githubusercontent.com/100534753/231487386-c256efa0-6b7a-4ce3-b5f1-6414a682551d.jpg)
