### ISSUE TITLE
might not be related to this repo but how to install cryptography??

### ISSUE THREAD

**Issue by enchanteddaemon** [Lost-MSth/Arcaea-server#108]
![Screenshot_2023-05-06-19-59-06-11_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/100534753/236620257-e24453b1-550d-4eca-95bf-0d0141561c09.jpg)

**Comment by Lost-MSth** [comment]
Actually, the debug log has given the instruction to deal with the problem. Or you can google it.

**Comment by guranu** [comment]
> ![Screenshot_2023-05-06-19-59-06-11_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/100534753/236620257-e24453b1-550d-4eca-95bf-0d0141561c09.jpg)

pkg install python-cryptography. pip install cryptography dosen't work in termux.
