### ISSUE TITLE
更新服务器版本后无法使用旧版数据库

### ISSUE THREAD

**Issue by FoXLinne** [Lost-MSth/Arcaea-server#11]
问题如题
这样一来每次更新都要重新注册账号，PTT重置，包括角色数值，技能在内的都要重新做调整。

**Comment by Lost-MSth** [comment]
啊？
后台有个数据库迁移的功能，不知道你用了没有
除了角色数据其它一般都可以同步，角色数据不同步主要是为了方便和官方一致（比如哪天616给角色觉醒一下）
直接复制数据库当然不行，表结构有变动的

**Comment by FoXLinne** [comment]
用的是网页后台的数据库更新功能 迁移过后登录原先账号会提示未知错误 当然重新注册一个账号是很正常的

**Comment by Lost-MSth** [comment]
啊这，请问迁移的两个版本号是多少

确定原来的账号消失了吗

**Comment by FoXLinne** [comment]
1.7迁移到1.9 以前从1.5-1.6 1.6-1.7都有相同的情况 账号的话从网页端可以正常查询 似乎也没有什么问题 数据库里的数据看起来也是正常的 但是游戏内登录不上去

**Comment by Lost-MSth** [comment]
以前的版本登录信息没有同步，所以需要重新登录(arcaea的登录是保存了登录信息而不是账户密码)

可以试一下重新输入账号密码登录

**Comment by FoXLinne** [comment]
现在去尝试一下

**Comment by FoXLinne** [comment]
已经解决 感谢

**Comment by FoXLinne** [comment]
……原来是这种问题

**Comment by FoXLinne** [comment]
另外还有一个问题 使用云端同步时会导致游戏闪退 包是3.4.0的 iOS端

**Comment by Lost-MSth** [comment]
ios端……我去找人试试，从来没遇到过这个问题，闪退一般是传给客户端的数据有问题

唔，我记得最近几个版本我改了数据同步相关的东西，隔离了云端存档和服务器best数据，可以抓包查一下同步的时候传来什么数据，大概就知道问题了

**Comment by Lost-MSth** [comment]
找到问题了，是ios独有的，安卓没问题
数据少一个createdAt

我这就push一下，但不做版本发布（等官方）
这改数据表结构了，需要后台迁移数据，直接复制无效
