### ISSUE TITLE
游玩Last时出现的BUG

### ISSUE THREAD

**Issue by Guzi422** [Lost-MSth/Arcaea-server#110]
使用的服务端版本是2.11.1（目前最新版），客户端版本是4.4.2c
在解锁Silent Answer的结局时，游玩Last会出现“发生了未知错误”
疑似客户端在POST服务端的/finale/finale_end接口的时候出错（以及你根本就没有开这个接口不报错就奇怪了.jpg）
这个接口与/finale/finale_start不一样，如果一样用空数据去填的话只会导致一直无法解锁Last的BYD难度（同样也不会解锁结局）

**Comment by Lost-MSth** [comment]
确实是漏了这个新加的接口，看了下，`/finale/finale_start` 接口应该没有处理任何数据，就是看 `success` 与否，按理说空数据不会导致问题
至于 Last 的两张 byd 谱子和两个结局的正常解锁过程我不是很清楚，能具体说说是哪个结局有问题吗

**Comment by Guzi422** [comment]
以目前来讲是Moment结局，Eternity结局也有可能，但是以客户端的明面运作的角度来讲，Eternity结局的触发前提就是需要有留存Moment的结局数据，否则无论怎样跑都只有Moment结局，现在是根本无法Start，所以两个结局都统一无法触发

我把`/finale/finale_start`的接口照搬过来还是能临时存储Moment的结局数据的（但是切回主界面就寄了），以及5和55的自动获取好像有问题，是没写吗（）

**Comment by Lost-MSth** [comment]
角色自动获取这肯定没写（ `finale_start` 或者 `finale_end` 估计就是通知服务端更新角色的，没觉得有什么别的用

我刚测试了一遍，不过我这里存档数据已经乱成一锅粥了也不怎么具备参考价值了，起始时 `Silent Answer` 包解锁但最终挑战的 `Testify` 空血量界面还在，点进去过一遍 `Testify` 后进结局剧情，到重新进游戏后两个结局 “完美之愿” 和 “最终之梦” 就全解了，之后 Track Complete 一遍 `Loveless Dress` 直接冒出来了 `Last` 所有难度了（）

我懵了已经，完全没法判断是什么鬼问题，算了，建议直接把存档全解开关打开，强制覆盖本地存档以解锁各种乱七八糟的开关）
