### ISSUE TITLE
how do i fix this? what's the problem in this?

### ISSUE THREAD

**Issue by enchanteddaemon** [Lost-MSth/Arcaea-server#115]
![Screenshot_2023-06-03-19-30-56-65_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/Lost-MSth/Arcaea-server/assets/100534753/ea41153a-4be0-49d8-96c7-11b730f5c44a)

it says permission denied

**Comment by Lost-MSth** [comment]
Please check the port conflict.
