### ISSUE TITLE
客户端无法连接

### ISSUE THREAD

**Issue by SRH603** [Lost-MSth/Arcaea-server#116]
试图登录时客户端显示无法连接至服务器，服务端则出现 "CONNECT arcapi-v2.lowiro.com:443 HTTP/1.1" 404 - 的信息
版本：4.4.3，系统：iOS15.5

**Comment by SRH603** [comment]
纠正，版本4.4.6

**Comment by Lost-MSth** [comment]
首先这不是我的服务端的信息，应该是抓包器的，然后，你确定地址对吗，这可是官服地址啊

不过 404 应该是 endpoint 错了，现在是 22 还是 23 来着，看一下写没写对

**Comment by Walkersifolia** [comment]
> 

我也出现了一样的问题，同为iOS（请问endpoint应该在哪里修改，config.py吗

**Comment by Lost-MSth** [comment]
https://github.com/Lost-MSth/Arcaea-server/wiki/Config-document

`GAME_API_PREFIX` 现在应该默认是 22 来着，wiki 忘记改了

https://github.com/Lost-MSth/Arcaea-server/blob/41409dee27d654452df8af7ee86510d5252df758/latest%20version/core/config_manager.py#L15C25-L15C25

**Comment by Walkersifolia** [comment]
> https://github.com/Lost-MSth/Arcaea-server/wiki/Config-document
> 
> `GAME_API_PREFIX` 现在应该默认是 22 来着，wiki 忘记改了
> 
> https://github.com/Lost-MSth/Arcaea-server/blob/41409dee27d654452df8af7ee86510d5252df758/latest%20version/core/config_manager.py#L15-L15

ok，谢谢，那最新的客户端可以连上吗，把服务端config.py里的版本留空的话

**Comment by Lost-MSth** [comment]
注释掉或者就别写，可以连的

**Comment by Walkersifolia** [comment]
> 注释掉或者就别写，可以连的

好的，谢谢，我去试试

**Comment by Walkersifolia** [comment]
> 注释掉或者就别写，可以连的

我试了，iOS设备会提示无法连接至服务器，服务端日志仍然一样`[2023-07-20 17:45:01,781] INFO in _internal: 192.168.3.6 - - [20/Jul/2023 17:45:01] "[33mCONNECT firebaselogging-pa.googleapis.com:443 HTTP/1.1[0m" 404 -`，安卓设备则是账号密码错误，点击登录服务端没有日志输出，但是的确连接到服务端了，以及数据库内的用户账号密码在客户端输入也是正确的，能正常打开浏览器的管理后台

**Comment by Lost-MSth** [comment]
`firebaselogging-pa.googleapis.com` 是 Firebase，跟游戏本体无关，显然客户端并没有成功连接服务端，如果是高版本客户端请确保已经做了各种必要操作了
https://github.com/Lost-MSth/Arcaea-server/issues/64#issuecomment-1257205897
