### ISSUE TITLE
Is it possible to disable accounts registration?

### ISSUE THREAD

**Issue by MrTerr1riym** [Lost-MSth/Arcaea-server#117]
Is there any way to disable the possibility of registering accounts, but without errors?
That is, I want to create 10 accounts for myself and friends and make it impossible to create new accounts, but it should still be possible to log in to existing accounts

**Comment by Lost-MSth** [comment]
Many ways. Changing `register` function in `/server/user.py` is the one of them. Either commenting the function or giving an error return is ok. It is surely that this way needs you have some knowledge about coding.

If you use a cloud server to deploy the server, maybe there can be a function in the control board, that can ban requests from a specific URL. It will work for banning the register game API (`http(s)://<Host>/<API Endpoint>/user   POST`).

**Comment by MrTerr1riym** [comment]
Thanks for helping me :)
