### ISSUE TITLE
ppt error 

### ISSUE THREAD

**Issue by firstWindow** [Lost-MSth/Arcaea-server#118]
why this error?
(Client and server; are latest versions)
![IMG_20230721_110022](https://github.com/Lost-MSth/Arcaea-server/assets/85897121/da53c848-18fc-4cce-b718-9f30f721d227)

**Comment by firstWindow** [comment]
![Screenshot_2023-07-28-20-26-33-32_3de306e3178de90c8b13f9c4ddd4419a](https://github.com/Lost-MSth/Arcaea-server/assets/85897121/96cf7107-acc3-4889-aecd-cf1509d28074)


On Android, server running in termux.
BTW my "song list" in 'database>songs>' is very old , it only has Dement,
Do I need to update it? 

![IMG_20230728_202827](https://github.com/Lost-MSth/Arcaea-server/assets/85897121/5904f84f-e530-42d2-bd17-776c92257932)

**Comment by Lost-MSth** [comment]
It has nothing to do with `songs` folder. Please check the chart const data of the songs in `arcaea_database.db` or in admin website. More details needed.

**Comment by firstWindow** [comment]
![Screenshot_2023-07-28-21-34-54-16_83ceefc07bf7d3f049298861e11860bc](https://github.com/Lost-MSth/Arcaea-server/assets/85897121/fe7243a2-b3f5-4c54-a021-8a78f44e2154)
this ? , what more details I can give?

**Comment by Lost-MSth** [comment]
It seems no problem. Emmm so strange. Can you reproduce the bug in every play?

Is it a fixed number? I doubt the client is magically modified.

**Comment by firstWindow** [comment]
Not in every play , it occurs only first after that it normal.
![IMG_20230729_100142](https://github.com/Lost-MSth/Arcaea-server/assets/85897121/85ee3da1-c4a5-4fc1-ac10-8d205332cb69)
![IMG_20230729_100130](https://github.com/Lost-MSth/Arcaea-server/assets/85897121/e9c53c47-e31c-4af8-aa4c-2d2965363e60)

No! returning in the main menu,the ptt is not normal ,

**Comment by Lost-MSth** [comment]
The user's ptt can be seen directly in the database. If it is normal, I believe the client has been magically modified. Change it to another client to see if it can be reproduced.
