### ISSUE TITLE
站点添加ssl后无法登录后台

### ISSUE THREAD

**Issue by OasisAkari** [Lost-MSth/Arcaea-server#12]
这次更新后出现了如题的情况

复现方法：
1.把服务器通过Nginx反代出去
2.给反代域名添加ssl
3.通过`https://<反代域名>/web`访问后台
4.尝试登录
5.点击登录后，登录页面会刷新，并没有进入后台页面
6.关闭ssl，通过`http://<反代域名>/web`访问后台并登录，可以正常进入后台页面
（我不是很会描述这个原谅我1551）

**Comment by Lost-MSth** [comment]
没事我听懂了，可是我不会解决（
这次更新后出现的问题？我倒是觉得这和版本无关，我从来没有设置ssl相关的东西（虽然其实flask可以走https）
f12一下看看吧，我觉得问题不太可能在服务端上，不过登录界面刷新到底是为什么这有点奇怪

**Comment by OasisAkari** [comment]
console里头也没看见什么错误啊..

**Comment by Lost-MSth** [comment]
f12是为了抓包啦（连js都没有不太可能报错
emm试试别的浏览器，比如ie之类的，可能也有影响

**Comment by OasisAkari** [comment]
啊吧啊吧啊吧（
我需要提供什么东西？不是很懂要发什么（

**Comment by Lost-MSth** [comment]
我也不是很懂我能干啥，毕竟这个有点难复现（我既没有ssl证书也没有域名也没有服务器，之前还把nginx删了

**Comment by OasisAkari** [comment]
我换成apache之后就好了 太草了
抱歉打扰了
