### ISSUE TITLE
服务端版本升级问题

### ISSUE THREAD

**Issue by SkeletoNCY** [Lost-MSth/Arcaea-server#122]
在服务端版本从2.10.3升级至最新版本后出现如下问题
[error.log](https://github.com/Lost-MSth/Arcaea-server/files/12262206/error.log)
请问下是否需要要对数据库做一些升级操作

**Comment by Lost-MSth** [comment]
呃，我想知道，你说的的 2.10.3 -> 2.11.2.x 版本升级是怎么做的，按理说第一次启动会检查数据库版本并自动更新的（

**Comment by htxzdfunny** [comment]
> 呃，我想知道，你说的 2.10.3 -> 2.11.2.x 版本升级是怎么做的，按理说第一次启动会检查数据库版本并自动更新的（

是这样的，但是我这边自动更新的时候经常会弹出来一堆报错，然后升级大失败
我没注意跑了几个月，今天发现数据库全乱完了，看 log 才发现升级没成功（

**Comment by htxzdfunny** [comment]
> > 呃，我想知道，你说的 2.10.3 -> 2.11.2.x 版本升级是怎么做的，按理说第一次启动会检查数据库版本并自动更新的（
> 
> 是这样的，但是我这边自动更新的时候经常会弹出来一堆报错，然后升级大失败 我没注意跑了几个月，今天发现数据库全乱完了，看 log 才发现升级没成功（

*乱完了：指玩家游玩记录混乱，A 的记录记到 B 身上，B 的记到 C 身上，还有一堆游玩时间戳为 1 的记录
我今天一上号就纳闷，我什么时候收了这么多歌，原来是别人打的蹿到我号上了（
![图片](https://github.com/Lost-MSth/Arcaea-server/assets/54425771/410c5894-9617-47b6-ab3d-3b0fab347d89)
![图片](https://github.com/Lost-MSth/Arcaea-server/assets/54425771/d7d0fa71-466c-4fb7-88ba-536601e80cf2)

**Comment by Lost-MSth** [comment]
唔，难道备份也被删掉了？就是在数据库更新时一定会保存一个旧数据库的备份

如果连备份也没有的话，数据表错乱的原因是什么呢，`user_id` 乱了？挺奇怪的

实在没办法的话，那就全部重开吧，用户量不大的话，跟用户协商一下，问问他们本地存档（就是非排行榜成绩）有没有乱，没乱就等重开后传上来，用来覆盖 b30 表吧（

**Comment by htxzdfunny** [comment]
> 唔，难道备份也被删掉了？就是在数据库更新时一定会保存一个旧数据库的备份
> 
> 如果连备份也没有的话，数据表错乱的原因是什么呢，`user_id` 乱了？挺奇怪的
> 
> 实在没办法的话，那就全部重开吧，用户量不大的话，跟用户协商一下，问问他们本地存档（就是非排行榜成绩）有没有乱，没乱就等重开后传上来，用来覆盖 b30 表吧（

啊我草我怎么在学校坐了三周牢了.jpg
我在 `database` 文件夹下面看到了个 `arcaea_log.db` ，似乎是每个玩家上传的游玩记录
我能通过这个来还原数据库吗？

**Comment by Lost-MSth** [comment]
那也只能还原成绩部分……而且主数据库 `user_id` 都乱了，记录数据库会不会乱呢

真把 `backup` 文件夹清空了啊（）

**Comment by Lost-MSth** [comment]
那也只能还原成绩部分……而且主数据库 `user_id` 都乱了，记录数据库会不会乱呢

真把 `backup` 文件夹清空了啊（）

**Comment by htxzdfunny** [comment]
> 那也只能还原成绩部分……而且主数据库 `user_id` 都乱了，记录数据库会不会乱呢
> 
> 真把 `backup` 文件夹清空了啊（）

看到 `backup` 文件夹了，我回滚一下试试（
