### ISSUE TITLE
Link play idx 512 restriction

### ISSUE THREAD

**Issue by MrTerr1riym** [Lost-MSth/Arcaea-server#124]
I'm having a problem with the playback on the link
When I try to run a song with idx above 512, I get a message that the song is not purchased from any player, but I'm alone in the lobby and songs with idx 512 and below don't give a similar error
How can this be fixed?

**Comment by Lost-MSth** [comment]
It's a restriction or a bug in the client. You need to mod the client. Or wait lowiro to fix it.
