### ISSUE TITLE
服务器请求 HTTP 404

### ISSUE THREAD

**Issue by xiaye6783** [Lost-MSth/Arcaea-server#125]
遇到这个问题该如何解决，客户端显示未知错误
网站访问和配置没有问题
![image](https://github.com/Lost-MSth/Arcaea-server/assets/110782638/5d94bd39-7e4e-4827-8815-247cdce04fc1)
我已经被这个问题困扰好久了（

**Comment by Lost-MSth** [comment]
客户端网址缺少后缀了，不建议这样干，强行要用的话服务端需要设置 `GAME_API_PREFIX` 为空字串

**Comment by xiaye6783** [comment]
可以了，感谢
