### ISSUE TITLE
Can't enter Axiom of the End

### ISSUE THREAD

**Issue by aliyafarhana** [Lost-MSth/Arcaea-server#129]
Hello, currently I just unlock the pack with the requirement (which is complete black fate and see VS-8, I already completed this and unlock Final Verdict) and after buy the pack when I started downloading it. It doesn't download I keep downloading and download and it still remains the same. I don't know what to do. I need help. How can I enter Axiom of the End? Is there a more requirements??

**Comment by Lost-MSth** [comment]
If downloading doesn't work well, it is suggested to check the files on the server, especially the videos.

No other requirements for entering the finale challenge.

**Comment by aliyafarhana** [comment]
I see. So, where I need to keep the videos?

**Comment by Lost-MSth** [comment]
https://github.com/Lost-MSth/Arcaea-server/wiki/Instruction-for-use#about-song-download

In the songs' folders, please put `video.mp4` and `video_audio.ogg`.

**Comment by aliyafarhana** [comment]
Oh okay. Wait, songs folder in apk or in database folder? Put them in the chart folder?
Like in songs/infinitestrife?

**Comment by Lost-MSth** [comment]
In each song's folder on the server, if you don't change the songlist file.

**Comment by aliyafarhana** [comment]
Ahh okay, thanks for helping me! I'll close this issue now.
