### ISSUE TITLE
Couldn't switch between normal and awaken character illustration if running on Linux

### ISSUE THREAD

**Issue by htk030** [Lost-MSth/Arcaea-server#13]
As title, here's the log/stacktrace

```[2021-01-25 08:09:22,490] ERROR in app: Exception on /latte/13/user/me/character/0/toggle_uncap [POST]                  
Traceback (most recent call last):                                                                                        
File "/usr/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()                                                                               
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
  reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
  raise value                                                                                                           
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
  rv = self.dispatch_request()                                                                                          
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File "/home/alarm/arcaea/server/auth.py", line 157, in wrapped_view
  return view(user_id, *args, **kwargs)                                                                                 
File "/home/alarm/arcaea/main.py", line 152, in character_uncap
  character_id = int(path[22:])
ValueError: invalid literal for int() with base 10: ''
```

While it's working just fine on Windows and change `int(path[22:])` to `int(path[21:])` somehow fixes this problem, maybe it's better to use split() to get the last portion of the URL?

Anyway, thanks for your awesome work. 👍

**Comment by Lost-MSth** [comment]
I am on the train and go back home so I cannot use my computer to test it.
But I guess the problem is the url has a double slash //(i don't know why arcaea has this strange problem). So I use a big range to match it and split it by counting the length of it.
Maybe Linux has changed url by itself so that server can not work with it correctly.
And if my guess is right, other three operations will also not work, including setting favorite partner, hiding ptt and notifing full stamina.

I will fix it in next version. Thank you for telling me this.

**Comment by htk030** [comment]
Yeah, I used print() to get the content of "path", and there's no double slash in there.
While illustration switching didn't work before I change the range, hiding ptt and setting favorite partner works just fine without modifying anything, dunno if full stamina notification works though.

**Comment by Lost-MSth** [comment]
Oh yes, it is not strange. I forgot that I used 'in' to judge the setting type so it will work.
I tried on Windows 10 and you can see there are double slash.
```bat
192.168.1.113 - - [25/Jan/2021 22:20:45] "POST /latte/13//user/me/character/2/toggle_uncap HTTP/1.1" 200 -
192.168.1.113 - - [25/Jan/2021 22:22:59] "POST /latte/13/user/me/setting/is_hide_rating HTTP/1.1" 200 -
192.168.1.113 - - [25/Jan/2021 22:23:47] "POST /latte/13/user/me/setting/max_stamina_notification_enabled HTTP/1.1" 200 -
192.168.1.113 - - [25/Jan/2021 22:24:01] "POST /latte/13//user/me/setting/favorite_character HTTP/1.1" 200 -
```

However when I use Linux, it is the same:
```bat
192.168.222.1 - - [26/Jan/2021 00:08:29] "POST /latte/13//user/me/character/2/toggle_uncap HTTP/1.1" 200 -
```
My virtual machine is Linux kali 5.5.0-kali2-amd64.

Maybe you use something other, like nginx or someting?
Well it is not important. I am just a little curious.

I find a way to do with double slash without import re.
```python
while '//' in path:
    path = path.replace('//', '/')
character_id = int(path[21:])
```
Emm.. I admit that it looks so stupid.lol :)
This will be added at next version.(I don't know when, it depends on lowiro.)

**Comment by htk030** [comment]
I'm using apache as reverse proxy, and your fix doesn't look that stupid, it looks much better than split() lol
