### ISSUE TITLE
April Fools and another bug (maybe)

### ISSUE THREAD

**Issue by aliyafarhana** [Lost-MSth/Arcaea-server#130]
Do I need to activate the april fools effects from lib? Because in my server config is "IS_APRILFOOLS = True". And after I end the game (which is I already played Testify) after the credit scene suddenly the game crashed. Is it from client or server?

**Comment by Lost-MSth** [comment]
April Fool function can only be used on the clients of April Fool's version, if there are no changes in lib file.

The crash is from the client, most likely due to magic modification and hard-coding.

**Comment by aliyafarhana** [comment]
If I enable april fools effects from lib, are the game will crash?

**Comment by Lost-MSth** [comment]
Theoretically not. But sorry I haven't known the practical effect.

**Comment by aliyafarhana** [comment]
Okay, anyway, the crash after Testify, what do you mean by magic modification and hard-coding?

**Comment by Lost-MSth** [comment]
Well, the client is changed via modifying the binary lib file and thus some program logics will be destructed. "Testify" is a very special song. So there must be many logics binding to it. If the modification is improper, the client crashes.

**Comment by aliyafarhana** [comment]
Ah okay, seems I need to travel through the lib again. And activate the April Fools effects. I'll close this issue.
