### ISSUE TITLE
Pack is not downloading

### ISSUE THREAD

**Issue by MrTerr1riym** [Lost-MSth/Arcaea-server#131]
Faced a problem that new pack is not installed (probably because of new video files "video_1080.mp4" & "video_720.mp4").
Help please
![IMG_20230928_191101](https://github.com/Lost-MSth/Arcaea-server/assets/64203805/9c92936b-e9de-48c7-84d7-d257bf6f1089)

Other songs download without problems

server 2.11.2.6
Arcaea 5.0.1

**Comment by Lost-MSth** [comment]
I know very little about this issue now. No data to test.

So should the video be downloaded? If yes, you can temporarily delete the `songlist` file in server's `songs` folder, and put the `video_1080.mp4` and `video_720.mp4` file in the `arghena` folder. Also you need to change some code in line 300 of `core/download.py` to `('video.mp4', 'video_audio.ogg', 'video_720.mp4', 'video_1080.mp4')`.

I am not sure whether it will work or not.

**Comment by MrTerr1riym** [comment]
I deleted songlist and modified the file
That helped, thank you
