### ISSUE TITLE
Error while downloading a songs

### ISSUE THREAD

**Issue by aliyafarhana** [Lost-MSth/Arcaea-server#133]
I have a problem where I can't download the songs. I already edit the download.py but when I try to download them, this error appears in my cmd `[2023-09-29 09:22:01,054] ERROR in _internal: (my ip) - - [29/Sep/2023 09:22:01] Request timed out: TimeoutError('timed out')`. I got this error while downloading Lasting Eden append pack (not sure for another append packs). It becomes more weird when another pack are works perfectly even the same error appears, means when it gives me `An error occurred while downloading the song. Please try again.` and then I restart download it again and again it works for another pack but for Lasting Eden append pack it doesn't work. I'm so confused right now. I think this is bug from the server not from the client. Sometimes it also doesn't works for another pack.

Another information:
`Server version: 2.11.2.6`
`Game version: 5.0.1c`

**Comment by Lost-MSth** [comment]
You said you did all things in #131 ?

`Request timed out` is irrelevance. There must be another reason.

**Comment by aliyafarhana** [comment]
Yes

**Comment by aliyafarhana** [comment]
Yes, and I think it caused by my internet connection (?)

**Comment by aliyafarhana** [comment]
Okay, it's my internet connection fault. Sorry. I'll close this issue.
