### ISSUE TITLE
Not sure how to fix this.

### ISSUE THREAD

**Issue by Mikaruuu** [Lost-MSth/Arcaea-server#137]
**What you want to know 你想知道什么**
Hey, does anyone know how to fix this error when trying to log in? I've connected to the server.

**Additional context 附加内容**
server ver: v2.11.2
arcaea ver: 5.1.0
android
![Screenshot_2023-10-28-13-50-53-121](https://github.com/Lost-MSth/Arcaea-server/assets/126860744/9072d92c-736f-4b71-8f1c-1f1d5c649f7d)

**Comment by Lost-MSth** [comment]
Why you firmly believe you connect to the server?

If it worked before and now it doesn't work, please restart the client and retype the username and the password.

**Comment by Mikaruuu** [comment]
Thank you, I'll try it and see how it goes.

**Comment by Mikaruuu** [comment]
> Why you firmly believe you connect to the server? More details please. I think there should be something in the console of the server.
> 
> If it worked before and now it doesn't work, please restart the client and retype the username and the password.

![Screenshot_2023-10-29-15-03-49-471.png](https://github.com/Lost-MSth/Arcaea-server/assets/126860744/1eb5d909-da7a-4b4e-aa62-8961843eccdb)

I've ran the server and it still comes up with the same issue. I think it's with my client but I'm not too sure.

**Comment by Lost-MSth** [comment]
Well. No network request log in console means that the client hasn't connected to the server. Please check the way you used. Make sure you have done all the changes / mods needed to the client.

**Comment by Mikaruuu** [comment]
> Well. No network request log in console means that the client hasn't connected to the server. Please check the way you used. Make sure you have done all the changes / mods needed to the client.

Thanks for telling me! Do you know anyway to fix this issue since I'm not too experienced with this kind of stuff?

**Comment by Lost-MSth** [comment]
If you have no experience about making clients connecting to the local server, please use a client under version 3.6.0 to try and learn.

There are many ways to do map remote. See other issues / discussions or other repos to get more information, or search in Google please.

**Comment by Lost-MSth** [comment]
Please make sure that you have taken the necessary steps to make the client connect to the local server. It is obviously that the updating message is from the official server.

**Comment by Mikaruuu** [comment]
> Please make sure that you have taken the necessary steps to make the client connect to the local server. It is obviously that the updating message is from the official server.

How do I forward the connection to a private server, if you don't mind telling? (Sorry if I'm rude www~)

**Comment by Mikaruuu** [comment]
> > Please make sure that you have taken the necessary steps to make the client connect to the local server. It is obviously that the updating message is from the official server.
> 
> How do I forward the connection to a private server, if you don't mind telling? (Sorry if I'm rude www~)

By the way, I've done everything to the client to be able to connect to the private server.

**Comment by Lost-MSth** [comment]
I do not know what you did. You have not show any details about the connection.

Moreover, cracking the client is relatively unrelated with this repo. You should get more information from other places. https://github.com/Lost-MSth/Arcaea-server/issues/64#issuecomment-1257205897

**Comment by Mikaruuu** [comment]
Thank you.
