### ISSUE TITLE
code 400, message Bad request syntax/Bad HTTP/0.9 request type 

### ISSUE THREAD

**Issue by enchanteddaemon** [Lost-MSth/Arcaea-server#139]
Info:
Server version: 1.7
Client version: 3.1.2

Platform: iOS
Server Platform: Android on Termux

How do I fix this code 400 error, I typed https on the binary file instead of http only.![Screenshot_2023-11-16-22-22-43-71_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/Lost-MSth/Arcaea-server/assets/100534753/f3b35eba-8e78-4d48-9624-8a0eb1558f8c)

**Comment by enchanteddaemon** [comment]
I think it needs certificate?

**Comment by enchanteddaemon** [comment]
I tried putting https because http don't work/doesn't have a response to the server

**Comment by Lost-MSth** [comment]
Server is not running under HTTPS. You need a domain name and SSL certificate if you want to use HTTPS.

**Comment by enchanteddaemon** [comment]
> Server is not running under HTTPS. You need a domain name and SSL certificate if you want to use HTTPS.

I got a SSL certificate, but how do I get a domain name?

**Comment by Lost-MSth** [comment]
One SSL certificate must bind one domain, and it can be only used in that domain. If you have no domain, why you think you got a SSL certificate? It is obviously useless. The HTTPS connection will be untrusted.

Most of domains requires fees. Normally, a device or a server with public IP, a domain, an SSL certificate, are all required for building an HTTPS server.

**Comment by BakaGzRay12456** [comment]
The iOS platform allows the utilization of HTTP by enabling the NSAppTransportSecurity-NSAllowsArbitraryLoads key to true in info.plist.
