### ISSUE TITLE
一个奇怪的打开方式和出现的问题

### ISSUE THREAD

**Issue by YorokobiMaster** [Lost-MSth/Arcaea-server#14]
系统是Win10 LTSC，前几天刚装的
Python3.9也是正常安装和配置好的
我用的方法是使用AdGuardHome，填写规则把本地服务器地址解析成arcapi.lowiro.com
应用到全局之后我整个网络都是可以直接指向服务器，
手机本地终端ping一下也能正常解析，
但问题来了——Arcaea客户端不认，Could not connect to online server
淦，亏我准备了这么多(
不过我也不确定我的AdGuardHome有没有正确配置，不过既然手机能ping通的话应该是没有问题的吧？
设备是MIX3，有root，面具，edxp，模块影响SSL验证的都关掉了
之前我是照着教程整的Charles，但是觉得太麻烦就(

**Comment by Lost-MSth** [comment]
按你说的应该没问题，有详细信息吗，比如抓包信息和服务端接受的信息之类的

**Comment by YorokobiMaster** [comment]
刚刚看到(然后火速手机上搞了小黄鸟看
连接arc服务器的时候是403 Forbidden，应该是我自己的问题？
电脑这边依然是没什么问题，网页是能正常进的(
我去问问搞dns的大佬(

**Comment by Lost-MSth** [comment]
服务器可能根本没接受到数据，是不是dns解析写反了？

**Comment by YorokobiMaster** [comment]
没有写反，正常解析......
查了一圈还不行，我开另一台电脑看看(

**Comment by Lost-MSth** [comment]
不，等等，我想起来了，之前用dns欺骗试过，成功不了是因为arcaea访问的链接是https，要证书
然后因为你root，Xposed大概可以屏蔽不信任的ssl证书这玩意，那么就能成
把main.py里面的app.run里面加个本地证书adhoc，改端口到443，服务器就可以接收https
或者用NGINX转发https流量到http上也行

**Comment by YorokobiMaster** [comment]
草(
太晚了，先开溜，早上爬起来再看看(
成功的话我就过来关issue(
总之非常感谢(
