### ISSUE TITLE
Force Updating Packs / Songs

### ISSUE THREAD

**Issue by CoreAndCrew** [Lost-MSth/Arcaea-server#143]
Is there a way to force update a downloaded song or pack like this? I'm curious

![Screenshot_20220708-175136](https://github.com/Lost-MSth/Arcaea-server/assets/69402267/3fd07e70-4144-468b-ac27-c045c04ab803)
(example from Arcaea Official Server)

**Comment by Lost-MSth** [comment]
Yes. Just change the file in the server, and then refresh the file hash in the web backend (or restart the server console).

**Comment by CoreAndCrew** [comment]
Cool, thanks for your response!
