### ISSUE TITLE
Beyond Breach Map

### ISSUE THREAD

**Issue by aliyafarhana** [Lost-MSth/Arcaea-server#148]
Can you make an update for this one? I really want to use the map. Well, I tried to make one by myself but I don't know how to add the "new_law" and "chain_info". What I know is "is_breached" and "disable_over" is boolean. Hope you can make an example for this one. Thank you!

**Comment by Lost-MSth** [comment]
`new_law: "over100_step50" | "frag50" | "lowlevel" | "antiheroism" | None` is just a string.

I am not sure whether `chain_info: dict` works or not. It is `{"id": <chain_id: str>, "index": <1, 2, 3, ...>}`

**Comment by aliyafarhana** [comment]
How I suppose to know for others? Like the chain_info. I found it in IDA when decompile Arcaea library. So, chain_info will look like this
{"id": "chain_id": test, "index": 1, 2, 3} ? Or something else? Can you explain more to me about this? I want to know about this. So I can do it by myself later.

**Comment by Lost-MSth** [comment]
For example, `{"id": "test", "index": 1}` is for the first map of the chain.

**Comment by aliyafarhana** [comment]
Ah I see, thank you. Btw will you add this for the server?. I hope you add it. I still need an example for this, in case if I forgot about it.

**Comment by Lost-MSth** [comment]
OK. I will add a breached map example at next version.

**Comment by aliyafarhana** [comment]
Thank you!
