### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by aliyafarhana** [Lost-MSth/Arcaea-server#149]
I have a question. Are all songs are required to have 0.aff, 1.aff, 2.aff? Because I was unlock my april fools song by making a map for it. So, 6 songs in one pack and I already unlock one but when I tried to download it, it still gives me download icon. How to fix this?

**Comment by Lost-MSth** [comment]
Yes. If one song needs to be downloaded, it should have chart files of all difficulties, except for the free pack's songs.

**Comment by aliyafarhana** [comment]
Is it count if I just copy the same file and just rename it to 0.aff and 1.aff?

**Comment by aliyafarhana** [comment]
Is it count if I just copy the same file and just rename it to 0.aff and 1.aff? And both folders or song database folder only?

**Comment by Lost-MSth** [comment]
Of course, any proper aff files can work. Put them on the servers' folders.

https://github.com/Lost-MSth/Arcaea-server/wiki/Q&A#why-not-success-in-downloading-songs-or-charts-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%AD%8C%E6%9B%B2%E6%88%96%E8%B0%B1%E9%9D%A2%E4%B8%8B%E8%BD%BD%E5%A4%B1%E8%B4%A5

**Comment by aliyafarhana** [comment]
Btw, what songlist in the song database folder does?

**Comment by Lost-MSth** [comment]
Provide the server with some information to limit the file range, or it may cause some bugs.

https://github.com/Lost-MSth/Arcaea-server/issues/60#issuecomment-1190837277

**Comment by aliyafarhana** [comment]
> Provide the server with some information to limit the file range, or it may cause some bugs.
> 
> [#60 (comment)](https://github.com/Lost-MSth/Arcaea-server/issues/60#issuecomment-1190837277)

Ah okay, thanks for helping me!
