### ISSUE TITLE
下载官方新歌曲的问题

### ISSUE THREAD

**Issue by 7lsu** [Lost-MSth/Arcaea-server#15]
### 环境
- Ubuntu 20.04 TLS
- Python 3.7.1
- Nginx 1.8 反代
- Android 10 over Root 系统信任证书
### 问题
下载歌曲时提示

> 下载歌曲时发生问题。请重试一次。

其他注册登录购买之类的功能工作的很nice，但在下载这里有点不明白，在解锁了音乐包后，下载音乐包里面的歌曲会出现错误提示，100%复现。

看了下wiki里的[关于歌曲下载](https://github.com/Lost-MSth/Arcaea-server/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%85%B3%E4%BA%8E%E6%AD%8C%E6%9B%B2%E4%B8%8B%E8%BD%BD)，可能是需要自己手动去添加歌曲的本地文件？想问问官方歌曲也需要这样嘛。还是可能我哪里没有配置到位（）

---

如下载cyaegha这首魔王抓包返回是这样：
（目测好像是没有数据，请问我要怎么添加"value"内的内容呀）
### Request

> GET https://arcapi.lowiro.com/latte/13/serve/download/me/song?sid=antithese&sid=corruption&sid=blackterritory&sid=viciousheroism&sid=cyaegha&url=true

### Response

> {"success":true,"value":{}}

**Comment by Lost-MSth** [comment]
如果是从服务器下载到客户端，服务器上当然需要歌曲以及谱面文件
官方下载是从官方的服务器上下载文件啦(超慢)，而且官网会检查用户是否拥有这首歌

比如: 如果上面你给的例子是官网的，你可能没有购买cyaegha这首所在曲包，导致没有返回
如果是本地服务器的，那就是songs文件夹里没有对应歌曲数据，导致没有返回

已经下载的文件可以从root手机的根目录data/data里面找，可以从官网下载然后放到本地的服务器上(当然找人要点数据也行)

**Comment by 7lsu** [comment]
啊明白了，感谢大佬，我去找找有没有人分享曲包
