### ISSUE TITLE
base.ogg not downloading (Dev Build)

### ISSUE THREAD

**Issue by CoreAndCrew** [Lost-MSth/Arcaea-server#156]
I am migrating songs from an old version of Arcaea to a new one so it can support ETR difficulty. I am getting a bug in which it is not downloading the base.ogg and thus cannot play the song. I am using server version v2.11.3.8 (the recent version in dev) and arcaea version 5.5.8c

![image](https://github.com/Lost-MSth/Arcaea-server/assets/69402267/f4e74b6f-26a4-4a2f-a1a5-fcd42767ee30)

**Comment by Lost-MSth** [comment]
Can you show me the folder structure of song data?

Do all songs have this problem?

**Comment by rlarhsid** [comment]
you too? I'm having the exact same problem. I think the current dev build has a problem.

**Comment by rlarhsid** [comment]
> Can you show me the folder structure of song data?
> 
> Do all songs have this problem?

To me, All of the songs have the problem. Plus, it seems the link play doesn't work, and PTT doesn't increase either.

**Comment by rlarhsid** [comment]
@Lost-MSth tested via the 2.11.3 master branch files, overwrting the "download.py" file in "/core" directory fixed this problem.

**Comment by Lost-MSth** [comment]
OK. I know it.

**Comment by firstWindow** [comment]
(4.aff ) file name is missing in core > download.py

FILE_NAMES = ['0.aff', '1.aff', '2.aff', '3.aff', **'4.aff'**,
                  'base.ogg', '3.ogg', 'video.mp4', 'video_audio.ogg', 'video_720.mp4', 'video_1080.mp4']

**Comment by CoreAndCrew** [comment]
Works now, thank you!

![image](https://github.com/Lost-MSth/Arcaea-server/assets/69402267/6ecc6e84-50a3-4edf-b5e4-f2915aca8448)
