### ISSUE TITLE
how to set the link play UDP server?

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#158]
I modded 5.5.8c arcaea, and everything works fine, including song downloads, PTT mechanisms, and etc.
However, the link play doesn't work, and I figured out that the port 82 (TCP server I changed for linkplay) opens successfully, but the port 81 (UDP server for linkplay) doesn't open at all.
I've tried changing the ports, changing the outbound / inbounds for the port in Windows Defender, Re-installing arcaea-server files and Flask, but nothing worked.

Would you tell me how to fix this? I'll screenshot the things that you say to attach if needed. Comment me please.

**Comment by Lost-MSth** [comment]
So, how did you check the UDP port 81? Show me the related output of `netstat -ano`.

**Comment by rlarhsid** [comment]
I checked the port 81 (UDP) closed via open port check tool (https://www.yougetsignal.com/tools/open-ports/).
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/3124660d-9f9b-403c-949a-33e29e293357)
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/0327831a-7f0a-4f74-85a0-216bbe3df4ad)
I'm using Wi-Fi, and Charles / VProxid to redirect arcaea to my local server. I did additional port-fowarding for port 80,81,82,2020,8888 (Charles HTTP and SOCKS), to use the server outside.

**Comment by rlarhsid** [comment]
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/80f04ae1-7cef-4d71-8ca2-f694c7b9e320)
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/722f5106-fb53-4d08-b324-659b6ec1117b)
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/c49dfede-f533-4542-b8be-a5fd6ad40583)

**Comment by Lost-MSth** [comment]
Hmmm UDP port cannot be easily checked by outside tools. By `netstat`, you can see the port is open.

VProxid... Nope, it doesn't support UDP, according to its [README](https://github.com/ProxidBean/VProxid).

**Comment by rlarhsid** [comment]
oh, I see. is there any other apps that could replace VProxid? sorry for asking too much.

**Comment by Lost-MSth** [comment]
VProxid's README puts [RProxid(root needed)](https://play.google.com/store/apps/details?id=com.lazybean.socksperapp).

Postern or others can work too.

**Comment by rlarhsid** [comment]
used proxifier, everything works fine. Thanks, I'll end this issue!
