### ISSUE TITLE
Songs doesnt downloads

### ISSUE THREAD

**Issue by MaximIce1** [Lost-MSth/Arcaea-server#159]
if i try to download all songs, server seems sending them, but client fails downloading them 
![image](https://github.com/Lost-MSth/Arcaea-server/assets/79106345/80d7c7c0-d5a0-4aa8-ac3f-91ee6796ba08)
![image](https://github.com/Lost-MSth/Arcaea-server/assets/79106345/9f821fa4-ad3f-4816-b32f-467eaee0c623)
arcaea 5.5.8c
server from dev branch

**Comment by Lost-MSth** [comment]
The server cannot get its address correctly. Please set the config item `DOWNLOAD_LINK_PREFIX`.

**Comment by MaximIce1** [comment]
how i should get prefix?
