### ISSUE TITLE
link play error, can't select any song above v4.4.

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#160]
I'm using 5.5.8c. I have all song packs at the server for v5.5.8, and I downloaded all the songs and can play them in single play. However, in Link Play, when I try to play songs that were released after v4.4, the games shows the screen that I don't own the song, even though I have already purchased it.
I saw a bug report that had the similar issue with me, and you said that it's the client's problem at that report. If it's the client's problem, could you speficially write what is wrong with the client, so I could fix it? If it's the server's problem, I'll hope you could fix this problem soon.

**Comment by Lost-MSth** [comment]
I have known the problem. The new difficulty changes something in Link Play. I need some time to adjust the server.

**Comment by rlarhsid** [comment]
it's good to hear that you are aware of this problem, I hope you could fix this problem. Thanks, I'll end this issue.
