### ISSUE TITLE
Link play bug in 5.6.0 Global client

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#161]
I'm using 5.6.0 Global client, which uses the contents bundle.
Using the latest server files causes two serious bugs to the link play system.

1. The difficulty of the gameplay is fixed to the host. For example, I am the host, and I invited my friend to the linkplay. If I select Ether Strike FTR, my friend has to play the FTR difficulty too, no matter what difficulty he chose. However, in the game, it is displayed that he's playing the difficulty he selected, which isn't.

2. Linkplay has a terrible stuttering. Tested via many clients, including armv7, armv8, 5.6.0c chinese, and global. It freezes almost every 30 seconds. This isn't my internet connection problems, as it never happened before, using the recent server files only caused this problem. Also, I have a decent internet speed.

+ not directly related to this problem, but it seems that the song "desive" isn't unlocked even though using the "WORLD_SONG_UNLOCK" feature in the config_manager. I made a map trying to unlock that song, but it didn't work.

**Comment by Lost-MSth** [comment]
1. It is a bug of client. Please report to lowiro.
2. I cannot replicate this issue. Link Play connection seems normal.
3. "desive" can be unlocked by cloud save full unlock function. I remember it contains multiple unlock conditions, and only world song unlock isn't enough.
