### ISSUE TITLE
database error? (latest server file)

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#162]
the latest server files (v2.11.3.10) seems like to have a weird error with the database system. No matter what database files I use, or even when I don't use the database files that I used and try to create a new db file, it brings me a sql error, and makes the server unable to do anything, including logging in, creating accounts, changing characters, etc.
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/5d700c38-b1b0-4581-96c1-a61221072f9b)
this is the screen that shows up when booting the server for the first time, without making any modifications to the config_manager.py or other files.
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/86ce1837-03c9-4f62-9598-e16a5658eabe)
this is the screen when I try imported the arcaea_database.db files that I was using, using the server config page.

**Comment by Lost-MSth** [comment]
Please do not change files in `/database/init` folder. It seems you add some packs in `pack.json`, which are not correct.

**Comment by rlarhsid** [comment]
overwriting the packs.json files to the original files fixed this issue, guess I shouldn't touch them more. Thanks for your advice.
