### ISSUE TITLE
character not unlocked after story endings

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#164]
I played Final Verdict pack, and cleared Testify through Axiom of the End, and saw the F-6 story. However, Fatalis Hikari, which should be added automatically after the steps above, wasn't added, and Testify wasn't even unlocked. Also, all tairitsu characters are supposed to be gone, but it wasn't. After I gave myself Fatalis Hikari using the world map and played the Axiom of the End again, Testify was unlocked. It seems like the character isn't added after watching the story cutscene (which is supposed to be added automatically), and can't unlock Testify if Fatalis Hikari is not added to the user character list.

Also, this issue happened same for the Silent Answer pack, the character "Hikari & Tairitsu" wasn't added either even after watching the "One Last Dream" ending, by playing "Last".

**Comment by rlarhsid** [comment]
+ seems like cloud save doesn't save the progress for Final Verdict pack, the progress was all wiped when logging out and logging in again. The cloud save only saves the state right before Testify unlock.

**Comment by Lost-MSth** [comment]
This is a known issue. The server won't add both "Hikari & Tairitsu" and "Hikari (Fatalis)" automatically. Moreover, I don't know the time of adding them, so it is hard to support it.

Please make sure `SAVE_FULL_UNLOCK = False` in config file. The full cloud save unlock fix the finale state to the state before the unlock of "Testify", which I have mentioned in doc.

**Comment by rlarhsid** [comment]
Well, it's sad to hear that I'll then just have to make additional world maps to unlock those characters.

Idk if this could help, but according to Arcaea Wiki, Hikari (Fatalis) should be added after completing "Testify", in Axiom of the End and reading the F-6 story, which requires the "Final Verdict" pack. Also, at this point, all Tairitsu characters should be unable to select. 

The character, "Hikari & Tairitsu", should be added after reading "One Last Dream" story. This story could be read by clearing the song, "Last", which is a hidden song, that could be unlocked by clearing "Loveless Dress". Both of these songs are included in "Silent Answer" pack, which is added after watching the F-7 story, and playing a light side song with Hikari, Hikari (Fracture), or Hikari (Fatalis). It's a hidden pack, a epilogue pack of "Final Verdict".

Watch these two videos for additional infos, sorry for bad language skills. I time-stamped at the first video, it's right after when clearing Testify at Axiom of the End. At the video, the story cutscene, F-6, is skipped due to spoiler issues, but normally it should appear.
https://youtu.be/jWm1xqO9qdU?t=2015
https://youtu.be/8V6dSp1qkNM

**Comment by rlarhsid** [comment]
> This is a known issue. The server won't add both "Hikari & Tairitsu" and "Hikari (Fatalis)" automatically. Moreover, I don't know the time of adding them, so it is hard to support it.
> 
> Please make sure `SAVE_FULL_UNLOCK = False` in config file. The full cloud save unlock fix the finale state to the state before the unlock of "Testify", which I have mentioned in doc.

Seems like you misunderstood the second one, sorry for not saying it clearly.

What I meant is, I already have cleared all the songs in Axiom of the End, without `SAVE_FULL_UNLOCK = true`. After clearing all the songs in Final Verdict pack, I unlocked the Silent Answer pack, and also cleared all the songs in it. And then, I saved my unlock progress to the cloud, using the "Cloud Save" feature, and logged out to play with my second account.

After I logged in to my original account a few days later, the "Silent Answer" pack, and all the songs in it, were gone. I checked the unlock state that I had saved to the cloud, and found that the progress saved to the cloud was right before playing testify. This is weird, as I saved my status "after" clearing testify, and even unlocked the hidden pack and songs.

**Comment by rlarhsid** [comment]
ah, I see. Sorry that I can't help you, I'm way too dumb to do things like these. Anyways, thanks for you replies!

**Comment by rlarhsid** [comment]
Tested more, and it seems that adding characters at the Finale stories are perfectly working. However, it seems that "Insight" character, which is added after the anomaly of "Arghena" isn't working yet. As this issue is quite simular with this issue, I just wrote this at here, and reopened the issue.

**Comment by Lost-MSth** [comment]
The partner can not be used at present, and even we cannot make sure the mechanism won't be changed in the future. Thus, I have no idea how to realize it.

**Comment by rlarhsid** [comment]
> The partner can not be used at present, and even we cannot make sure the mechanism won't be changed in the future. Thus, I have no idea how to realize it.

What I meant was that the characters aren't added to the user at all (even after all the unlock conditions are satisfied). I know that the character can't be selected and be used yet now. However, by enabling `CHARACTER_FULL_UNLOCK`, the 'Insight' character is added to the user, so I assumed that the server doesn't have the codes for adding the 'Insight' character to the user after unlocking 'Arghena". If not adding this character after the unlock of 'Arghena' is intended, which is supposed to be added according to the original server, I'll close this issue.

**Comment by Lost-MSth** [comment]
We cannot ensure this partner is just added at the time when the song unlocks. The display or disappear of this partner is controlled by the client mainly.

Moreover, we cannot ensure the way to obtain or use the partner will not change. The plot of this part is in building.

So, I have no plan to realize this function. If you want it, you can change the code by yourself.

**Comment by rlarhsid** [comment]
I see, I'll then try by myself for adding the characters. Thanks for the answers.
