### ISSUE TITLE
Error with Recent30 enhancement

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#165]
Before I start, I'll apologize for making too much bug reports, sorry if making these bothers you. Let me know if I'm making too much useless bug reports.

![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/64750fed-3ebd-4eb8-a610-655503a41687)
This image is when I try to bring the database file (database.db) that I was using, which is [this commit](https://github.com/Lost-MSth/Arcaea-server/commit/efedd969086b6ef9699a0a043b989668c9964204). I only changed the server ports for game testing in that screen, and didn't change anything else.

I saw your latest server files, which fixed the character automatical adding, and tried to use it. However, it seems that I can't bring the database that I was using. Also, the PTT systems doesn't seem to work, which is done at the game result screen.

Sorry for wrting a bit vague. I'll add additional information when I have more time.

**Comment by Lost-MSth** [comment]
Have you update the `database/init` folder? There are some changes about `recent30` table.

**Comment by rlarhsid** [comment]
I think probably not. How could I update it?
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/a2a68b5b-ee49-47d1-91ca-af1f2e174fdd)
This image is the thing that I said "PTT system not working". After the song finishes, the client says "Unable to post score to the server", and the server is like this.

**Comment by rlarhsid** [comment]
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/82bd24ce-6f4b-473e-923a-f44cca20bd32)
changing the all the files except course.json (I made custom courses) in the /init folder from the latest server fixed at least this issue, but what at cost...

> I think probably not. How could I update it? ![image](https://private-user-images.githubusercontent.com/131584438/328248549-a2a68b5b-ee49-47d1-91ca-af1f2e174fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTM0NTksIm5iZiI6MTcxNTAxMzE1OSwicGF0aCI6Ii8xMzE1ODQ0MzgvMzI4MjQ4NTQ5LWEyYTY4YjViLWVlNDktNDdkMS05MWNhLWFmMWYyZTE3NGZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNjMyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGE5MGNlYjg3NjZlNTZmZWI1NThiM2ZmZTFlMTU2ODA4ZDc4NGIzOWZiZWVmYzYyM2MwNjdiNWMyYTY3ZmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EBpVqolu4fQO8vY0SqixOzouivIKOAQqRISd8cNKz9E) This image is the thing that I said "PTT system not working". After the song finishes, the client says "Unable to post score to the server", and the server is like this.

**Comment by Lost-MSth** [comment]
It seems the database is broken when you incorrectly updated it. You can get the backup db in the `database/backup` folder. Replace the current db with it and then restart the server. I hope there will be no problem.
