### ISSUE TITLE
A few world mode maps are missing

### ISSUE THREAD

**Issue by FishiaT** [Lost-MSth/Arcaea-server#166]
For example in Chapter 1, 1-5, 1-6 and 1-S are all missing. I have not checked other chapters but there are likely other ones that are missing too.

**Comment by rlarhsid** [comment]
Yeah, most of the map files are currently missing, only a few maps are made and others aren't. Probably you'll have to make by yourself, by reading the map files (.json) that are in the /database/maps folder. At least I did by that method.

**Comment by Lost-MSth** [comment]
I think the world map part is data, which are freely customizable. Only some are given as examples.

**Comment by FishiaT** [comment]
Yes, the world mode maps are all data-driven.
I would like to ask if you got the maps by dumping it from the game or did you reconstruct it yourself through data from the Arcaea wiki perhaps? I wanted to add all maps from vanilla onto the private server so that the experience will not differ much from original.

**Comment by Lost-MSth** [comment]
A long time ago, I directly obtained some data from the official server, but now it's too difficult to do so.

The data from wiki are also detailed and accurate. The difficulty lies in how to convert them.

**Comment by FishiaT** [comment]
Say if I were to obtain it from the official server, does the game retrieve map data after you access it or when you access world mode?

**Comment by Lost-MSth** [comment]
If I correctly understand what you asked, I think the answer is both. The client gets some parts of the world map data when you open the game, and then get more detailed data when you enter the world mode.
