### ISSUE TITLE
iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退

### ISSUE THREAD

**Issue by FoXLinne** [Lost-MSth/Arcaea-server#17]
问题如题，闪退处在logo出来的地方，点击进入游戏门关上就闪退了
目前知道的解决方法就是把解锁的内容重新封回去（删除数据库内对应内容）

**Comment by Lost-MSth** [comment]
没ios设备测试，安卓刚又试了一下没问题(
ios客户端和安卓客户端代码不一样，炸了很日常((((

首先看一下服务器报错日志，error.log，可能是空的，那就没啥问题

然后……然后我也不知道了啊)

推断一下，解锁不解锁的区别只是曲包和单曲那一条会变，该不会是ios客户端版本旧了没有新曲信息闪退了吧

**Comment by FoXLinne** [comment]
我这边在数据库里对曲包和单曲主动做了修改，因为是自制客户端，所以pack id都要手动录入一遍的，所以先排除客户端太老的问题（

**Comment by FoXLinne** [comment]
我这边因为ip过长超过了2进制文件限度，所以手动尝试把api里的/latte/13变成了/13 测试下来是基本正常，但是我只改了main脚本里的内容，会不会是其他的文件里还有api没有改动的缘故

**Comment by FoXLinne** [comment]
话说wiki是不是都变成空文件了（

**Comment by Lost-MSth** [comment]
应该不是这个问题吧，进入游戏第一个请求的是aggregate，返回的里面有曲包和单曲信息，你手动改的话要改全，还要删掉原来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
我这边因为ip过长超过了2进制文件限度，所以手动尝试把api里的/latte/13变成了/13 测试下来是基本正常，但是我只改了main脚本里的内容，会不会是其他的文件里还有api没有改动的缘故

**Comment by Lost-MSth** [comment]
嘛，加密了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 凌晨0:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
话说wiki是不是都变成空文件了（

**Comment by FoXLinne** [comment]
mainpy一共改了25处（其实wiki我也不是很需要

**Comment by Lost-MSth** [comment]
是25处，这不影响的啦，会不会是版本迁移过了，然后数据库里多了官服数据？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 凌晨0:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
mainpy一共改了25处（其实wiki我也不是很需要

**Comment by FoXLinne** [comment]
服务器版本迁移了，但是我是因为老版闪退才升级到新版的
客户端我一直是3.5.1 包里曲子也是官谱自制都有的

**Comment by FoXLinne** [comment]
官服数据是指什么样的数据，比如官方客户端的成绩之类的吗，我做的是共存，还特地做了放串数据处理

**Comment by Lost-MSth** [comment]
咳，wait，您是怎么改pack和single数据的，该不会只是动了json吧

**Comment by FoXLinne** [comment]
我没动json，我是数据库手动修改（

**Comment by FoXLinne** [comment]
自从这个功能实装以来我就发现光动json好像没啥用处

**Comment by Lost-MSth** [comment]
嗯，确实只改json没用，改数据库肯定对的

然后另一个问题我刚刚想起来，你说做了共存，那共存自制里没有官服曲子对吧，但服务器pack single里有，数据照样发过去的，会不会因为这个崩了？

**Comment by FoXLinne** [comment]
[2021-03-20 20:04:48,977] ERROR in sql: ['Traceback (most recent call last):\n', '  File "E:\\Desktop\\v2.3\\server\\arcscore.py", line 594, in arc_all_get\n    scores_data = json.loads(x[1])[""]\n', '

**Comment by FoXLinne** [comment]
error.log他出现了（

**Comment by Lost-MSth** [comment]
这个……记得有人提过了，是云端存档里面有一条异常数据，不是很影响，删掉就行 应该不会导致进游戏闪退------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月21日(星期天) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)

**Comment by FoXLinne** [comment]
经过我的研究，就是这一条出了问题（

**Comment by Lost-MSth** [comment]
啊？那里能触发的错误就是云端同步失败而已啊（）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 中午1:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
经过我的研究，就是这一条出了问题（

**Comment by FoXLinne** [comment]
是云端同步后云端依旧没有数据，而将错误数据重新读取到客户端就会导致闪退

**Comment by Lost-MSth** [comment]
但……实际上触发错误后服务器返回的是空数据，这也能出bug 616谁写的ios代码（




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 中午1:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
是云端同步后云端依旧没有数据，而将错误数据重新读取到客户端就会导致闪退

**Comment by FoXLinne** [comment]
另外关于曲包锁问题，我现在一条一条实验，最后发现似乎是我返回的曲包数据过多了的问题

**Comment by Lost-MSth** [comment]
这倒是正常（）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 中午1:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
另外关于曲包锁问题，我现在一条一条实验，最后发现似乎是我返回的曲包数据过多了的问题

**Comment by FoXLinne** [comment]
所以数据同步这个594行的问题应该怎么解决呢（

**Comment by FoXLinne** [comment]
现在同步功能算是废了

**Comment by Lost-MSth** [comment]
呃？是ios端上传的数据有问题吧，能抓个包看看吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 下午2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
现在同步功能算是废了

**Comment by FoXLinne** [comment]
[2021-03-21 14:50:40,188] ERROR in sql: ['Traceback (most recent call last):\n', '  File "E:\\桌面\\v2.3\\server\\auth.py", line 171, in wrapped_view\n    token = headers[\'Authorization\']\n', '  File "C:\\Users\\AkiraEXE\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\werkzeug\\datastructures.py", line 1463, in __getitem__\n    return _unicodify_header_value(self.environ["HTTP_" + key])\n', "KeyError: 'HTTP_AUTHORIZATION'\n"]
[2021-03-21 14:50:40,189] INFO in _internal: 192.168.0.4 - - [21/Mar/2021 14:50:40] "[37mGET /13/user/me/save HTTP/1.1[0m" 200 -

**Comment by Lost-MSth** [comment]
这是未授权访问，请求没有token

**Comment by FoXLinne** [comment]
自裁了，刚学会抓包

**Comment by FoXLinne** [comment]
post到的unlock_list为空

**Comment by FoXLinne** [comment]
而点击云端同步按钮时候get到的数据是全部要残片解锁的歌曲，也就是完整的unlock list

**Comment by Lost-MSth** [comment]
空指的是这样 "":[] 吗？那就没问题
get得到的是unlock list写死的，为了解锁world_song和那几个特殊曲子




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
而点击云端同步按钮时候get到的数据是全部要残片解锁的歌曲，也就是完整的unlock list

**Comment by FoXLinne** [comment]
或许是写死的内容导致我的存档里多了本不该有的新版本歌曲，我是3.5.1的客户端，用2.3（3.5.2)的服务器

**Comment by Lost-MSth** [comment]
多了也会炸嘛，那就去arcscore.py里删掉（所以自制稳炸？）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月21日(星期天) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] iOS，用户购买信息修改，全部解锁后导致进入游戏时闪退 (#17)





 
或许是写死的内容导致我的存档里多了本不该有的新版本歌曲，我是3.5.1的客户端，用2.3（3.5.2)的服务器

**Comment by FoXLinne** [comment]
根据对3.4.1，3.5.0版本的壳子进行测试后发现存档不同步问题为3.5.1特有bug，回退至3.4.1版本后正常使用，屑616屑
