### ISSUE TITLE
服务器出现code400 http/0.9

### ISSUE THREAD

**Issue by huan201** [Lost-MSth/Arcaea-server#170]
本人环境：
设备：android 13（iqoo z7）
客户端：arcaea5.6.0（已修改了客户端可以连接服务器）proxifier（代理）
服务器：2.11.3（charles：http环境）
状况：
可以登陆服务器，歌曲数据已录入，但下载歌曲时客户端会卡住，服务端会报错
![Uploading IMG_20240524_230052.jpg…]()
![Uploading IMG_20240524_230108.jpg…]()
![Uploading IMG_20240524_232333.jpg…]()
![Uploading IMG_20240524_232327.jpg…]()

**Comment by huan201** [comment]
测 没传上来
![Uploading IMG_20240524_230052.jpg…]()
![Uploading IMG_20240524_230108.jpg…]()
![Uploading IMG_20240524_232327.jpg…]()
![Uploading IMG_20240524_232333.jpg…]()

**Comment by huan201** [comment]
![IMG_20240524_230052](https://github.com/Lost-MSth/Arcaea-server/assets/88644963/16f6ae27-deb8-452e-9ad7-80558d96352b)
![IMG_20240524_230108](https://github.com/Lost-MSth/Arcaea-server/assets/88644963/bcb687ce-4169-4f50-9bb0-16878cfbfb5a)
![IMG_20240524_232327](https://github.com/Lost-MSth/Arcaea-server/assets/88644963/ecf1153b-afbd-44d0-bec3-6d47153bb9a1)
![IMG_20240524_232333](https://github.com/Lost-MSth/Arcaea-server/assets/88644963/d834e6ce-9e99-4d42-955d-6e0ea666d1d2)

**Comment by Lost-MSth** [comment]
代理和转发的问题，400 是把 https 请求直接发给服务端导致的

**Comment by huan201** [comment]
> 代理和转发的问题，400 是把 https 请求直接发给服务端导致的

那么大佬，我给服务器搞个https？ 但自签证书可以吗（他们其他人好像没这问题）

**Comment by Lost-MSth** [comment]
不是，Charles 和代理设置有问题，https 转发到 http 不就好了（

**Comment by huan201** [comment]
> 不是，Charles 和代理设置有问题，https 转发到 http 不就好了（

啊？
![Screenshot_20240525_214256](https://github.com/Lost-MSth/Arcaea-server/assets/88644963/7d13094b-9249-4c58-ad98-4677c7d1b2c4)
![IMG_20240525_214248](https://github.com/Lost-MSth/Arcaea-server/assets/88644963/6ac176a4-3229-4cd5-94d8-87bec120bca9)
这样不行吗

**Comment by Lost-MSth** [comment]
可以，但是你 charles 里面可全是 unknown 啊，起码你转发的请求应该能被抓到

**Comment by huan201** [comment]
> 可以，但是你 charles 里面可全是 unknown 啊，起码你转发的请求应该能被抓到

啊？ 那是我charles没设置好？

**Comment by huan201** [comment]
> 可以，但是你 charles 里面可全是 unknown 啊，起码你转发的请求应该能被抓到

大佬可以给点帮助吗

**Comment by Lost-MSth** [comment]
到网上搜一下，大概是 charles 证书没搞好吧

**Comment by LoaderTime** [comment]
@Lost-MSth 
您好。

因为在最新版试着下载曲目文件时又出现了这个问题，问题的来源也一样，为了避免`Duplicate`，所以想直接在这个issue下继续提问。

使用的是`Arcaea c6.5.3`版本，服务器使用的是dev-branch的最新版(97b86a4)。

目前发生的情况与issue中的服务端日志几乎一致，**Charles内部的抓包信息除外**（抓包信息在附加内容中）。

`DOWNLOAD_LINK_PREFIX`为空（自动获取），`GAME_API_PREFIX`已正常设置。

我记得Charles的证书只管抓包，转发之后就什么都不管了，应该不是这个问题。既然能够登录，那么也应该配置好https转http了。

期待您的回复，感激不尽！

附加内容（本地ip露出来应该没事，服务端的日志也有必要所以也加上了）：

![Image](https://github.com/user-attachments/assets/a00c81ea-c47b-4dd5-b968-40af52785db9)

![Image](https://github.com/user-attachments/assets/86ba6515-5b87-4432-9601-853b09463a1f)

**Comment by Lost-MSth** [comment]
只是下载出问题吗，那你看一下抓包数据里面 '/serve/download/me/song' 的回包里的地址对不对，自动获取不一定对。

**Comment by LoaderTime** [comment]
> 只是下载出问题吗，那你看一下抓包数据里面 '/serve/download/me/song' 的回包里的地址对不对，自动获取不一定对。

再看了一遍，发现也有Socket的连接，内容为`Unknown`，报错也一样。是`SSL: Unsupported or unrecognized SSL message`。

所以回去试了下原版是否能够抓包，答案是可以。（图片在附加内容中）

~~有没有可能是在https转http时，协议内容转换的过程中出了点问题？~~
或者说跟图片里的`https://arcaea.lowiro-cdn.net`这个地址有关？因为歌曲文件需要下载的内容均出现在这个地址下。

附加内容：

![Image](https://github.com/user-attachments/assets/a3d81235-cb8e-49cd-a119-c82ca8882a2e)

**Comment by LoaderTime** [comment]
> 或者说跟图片里的`https://arcaea.lowiro-cdn.net`这个地址有关？因为歌曲文件需要下载的内容均出现在这个地址下。

问题解决了，向`DOWNLOAD_LINK_PREFIX`加入`https://arcaea.lowiro-cdn.net/download`即可。

话说这样也真方便了，一个地址解决问题。

感谢您的回复！

**Comment by Lost-MSth** [comment]
啊？不是，你确定吗，`arcaea.lowiro-cdn.net` 明显是官方的东西啊

**Comment by LoaderTime** [comment]
我知道这很怪，但是莫名其妙地就好了。毕竟后面的注释写的是`http://***.com/download/`（？）

顺带把这个地址重定向到服务器了。或者是只需要一个`/download`的后缀？

Log日志：

```
[2025-06-21 20:47:35,229] INFO in _internal: 192.168.3.28 - - [21/Jun/2025 20:47:35] "GET /coldwind/35/serve/download/me/song?sid=diode&url=true HTTP/1.1" 200 -
[2025-06-21 20:47:41,610] INFO in _internal: 192.168.3.28 - - [21/Jun/2025 20:47:41] "GET /download/diode/2.aff?t=57a1a96c6c2e6b88df28661502242325 HTTP/1.1" 200 -
[2025-06-21 20:47:41,635] INFO in _internal: 192.168.3.28 - - [21/Jun/2025 20:47:41] "GET /download/diode/1.aff?t=d0eedb4568966ebdbcb736b6f31ed450 HTTP/1.1" 200 -
[2025-06-21 20:47:41,637] INFO in _internal: 192.168.3.28 - - [21/Jun/2025 20:47:41] "GET /download/diode/base.ogg?t=e2034edecbb55f6cafebeed84e5764d3 HTTP/1.1" 200 -
[2025-06-21 20:47:41,796] INFO in _internal: 192.168.3.28 - - [21/Jun/2025 20:47:41] "GET /download/diode/0.aff?t=60d683ce66c4a85f4193c6f391ea5073 HTTP/1.1" 200 -
[2025-06-21 20:48:00,511] INFO in _internal: 192.168.3.28 - - [21/Jun/2025 20:48:00] "GET /coldwind/35/score/song/me?song_id=ddd&difficulty=2&start=4&limit=18 HTTP/1.1" 200 -
```

API设置：
```
    歌曲下载地址前缀，留空则自动获取
    Song download address prefix
    If left blank, it will be obtained automatically.
    '''
    DOWNLOAD_LINK_PREFIX = 'https://arcaea.lowiro-cdn.net/download/'  # http://***.com/download/
    '''
```

额外内容：

如果这样不行的话，把配置里的`https://arcaea.lowiro-cdn.net/download/`里的`https`改成`http`就行了。

然后把`http://arcaea.lowiro-cdn.net/*`重定向到你自己服务器的地址。

**Comment by Lost-MSth** [comment]
哦你把它重定向了，那没事了，这样也行，有点怪倒是。
