### ISSUE TITLE
a function for making arcaea_database.db able to be downloaded

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#171]
I see that I can upload the arcaea_databse.db file through the admin web page on any network, if I do some additional port-fowarding settings on my router.
However, It seems that there aren't any functions for downloading the .db file, it would be helpful if both downloading & uploading is possible. It would let people able to fix the .db files instantly if any errors happen / or just let people like me add some accounts directly to the .db or edit some data when they aren't able to access the server directly.
As this is more like an additional feature, nevermind this report if this would be a bit complex or troublesome.

**Comment by Lost-MSth** [comment]
Well, the function of uploading database is used to do manual updating. It should not be used to change data in it, and it may cause some safety issues.

If you want to change something at the file level, the more recommended way is using RDP or SSH.

Additionally, I have indeed considered the solution of directly operating the database on the front-end page, although this may be a bit unsafe. But, this doesn't seem like a simple thing; at least I won't be able to achieve it in the near future.

**Comment by rlarhsid** [comment]
As long as the data in the .db file is edited properly, it won't make any issues. However, I understand your opinions, as you said I could just use SSH instead. Thanks for replying.
