### ISSUE TITLE
adding a simple score page

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#172]
I remember that the official Arcaea server has a function for users to check their own scores / results through the web, and so does repo has a simular function by the "Single User Score" page. However, currently that page is only available with the admin account, which leads other users unavailable to check their scores through the web or ask to the server admin all the time when they want to know their scores. It would be nice if there's a simple score checking page such as "[server ip address]:[port]/userscore" or something, and lets users check their scores by entering the username. Not necessary, but it would also be a good function if it is possible to let people know the exact scores, and other people's ranks about the global ranking (idk the exact name, I'm talking about the rank that is shown next to the username in the client when logged in). I'll wait for your replies, thanks for reading.

**Comment by Lost-MSth** [comment]
In a short word, it has been in progress, but it may take a very large amount of time and effort.

I have given some APIs for users and admins to get some information from the server, including users' scores. You can use them although API may not be stable in futher's commit. So, if you really need it now, you can implement a frontend and call APIs to get data.

For backend webpages, I have discarded it and only do some little changes now if needed. I am considering another admin frontend or another way. But unfortunately, it seems to be not easy. The progress in this part is quite slow.
