### ISSUE TITLE
a new arcaea_database.db repo

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#173]
Seems like the arcaea_database.db files that are on your README.md are no longer maintained, so I made my own repo which supports the latest 5.7.0 arcaea songs. https://github.com/rlarhsid/arcaea-database/
<img width="919" alt="image" src="https://github.com/Lost-MSth/Arcaea-server/assets/131584438/ba7b9a1f-1a2f-427f-91a5-40a403dcb558">
if you need, you could replace or add my repo to your README, or nvm if you don't need.

**Comment by Lost-MSth** [comment]
See it. Moreover, prefer `arcsong.db` only. Like <https://github.com/CuSO4Deposit/ArcaeaSongDatabase> or <https://github.com/Arcaea-Infinity/ArcaeaSongDatabase>.

**Comment by rlarhsid** [comment]
Ah, I see. Maybe I could try to make another `arcsong.db`, but can't assure when I could exactly come up with. Anyways, thanks for telling it.
