### ISSUE TITLE
Request Timed Out Error when using HTTPS

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#174]
Well, it's litterally what is said on the title. I've recently switched the server to HTTPS, using Let's Encrypt. Everything seems to work fine and the server is running HTTPS correctly, but the server console gives me the "Request timed out: TimeoutError('The read operation timed out')" everytime. Seems like it doesn't affect anything, at least on the admin web page, is there any solutions for this, or did I config something wrong?

**Comment by Lost-MSth** [comment]
No problem. I meet this message before. It seems no affect. At least, it is not something wrong on server; it looks like an issue of some python module.

**Comment by rlarhsid** [comment]
It's good to hear that there aren't any affects for this issue, and it's not because of me. Thanks!
