### ISSUE TITLE
small typo mistake on the latest dev version

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#175]
there's a typo mistake in /core/sql.py.
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/0ea70e78-469f-45e9-8074-1913722cb7f1)
this causes updating the arcaea_database.db on the admin web unable.

**Comment by Lost-MSth** [comment]
I see.

dd0bc64c93705b029d9d2c45d7c85d3b0bd94cd2 fixed

**Comment by rlarhsid** [comment]
woah was making a pull request, guess it was useless as you fixed faster than me. Thanks!
