### ISSUE TITLE
Arghena not downloading when "songlist" file exists

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#177]
When the file `songlist` exists, and the server config `DOWNLOAD_FORBID_WHEN_NO_ITEM` is set to TRUE, the Arghena couldn't be downloaded, eventually causing the client unable to play Lasting Eden Chapter 2.
![image](https://github.com/Lost-MSth/Arcaea-server/assets/131584438/cca118cc-73b9-4d41-86aa-d3f4bb52e8f2)
You could see that the server doesn't send the `video_1080.mp4`. I have tested without the `songlist` file, and it worked. Thus, this is not about the problem of the song files or the server config. Guess there's something wrong on `DOWNLOAD_FORBID_WHEN_NO_ITEM`.
And to be honest, I don't the feature is currently working either. Even with the option on, the server sends all of the song files, whether the user had purchased or not. I know that this is a experimental feature and isn't stable yet, but it would be nice if you could fix and make this feature stable someday.

**Comment by Lost-MSth** [comment]
Can you show me the "Arghena" item in the `songlist` file, or is it the official one?

`DOWNLOAD_FORBID_WHEN_NO_ITEM` must work with the `songlist` file.

**Comment by rlarhsid** [comment]
the songlist file I'm using is from the official 5.7.1 bundle.

**Comment by rlarhsid** [comment]
```
{
            "idx": 352,
            "id": "arghena",
            "title_localized": {
                "en": "Arghena"
            },
            "artist": "Feryquitous vs Laur",
            "search_title": {
                "ja": [
                    "あーげな",
                    "あげな"
                ],
                "ko": [
                    "아르게나",
                    "아게나"
                ]
            },
            "search_artist": {
                "ja": [
                    "ふぇりきたす",
                    "らうる"
                ],
                "ko": [
                    "페리퀴토스",
                    "라우르"
                ]
            },
            "bpm": "185",
            "bpm_base": 185,
            "set": "eden_append_1",
            "purchase": "eden_append_1",
            "audioPreview": 0,
            "audioPreviewEnd": 0,
            "side": 1,
            "bg": "arghena",
            "bg_inverse": "arghena",
            "remote_dl": true,
            "world_unlock": false,
            "date": 1695772808,
            "version": "5.0",
            "difficulties": [
                {
                    "ratingClass": 0,
                    "chartDesigner": "第一識 \"Reality\"",
                    "jacketDesigner": "すずなし",
                    "rating": 7
                },
                {
                    "ratingClass": 1,
                    "chartDesigner": "第二識 \"Causality\"",
                    "jacketDesigner": "すずなし",
                    "rating": 9
                },
                {
                    "ratingClass": 2,
                    "chartDesigner": "第三識 \"Pluriversality\"",
                    "jacketDesigner": "すずなし",
                    "rating": 11
                }
            ],
            "additional_files": [
                {"file_name": "video_720.mp4", "requirement": "low_res"},
                {"file_name": "video_1080.mp4", "requirement": "hi_res"}
            ]
        },
```

Here's the part that is in the `songlist` file. It's the part of Arghena.

**Comment by rlarhsid** [comment]
> Can you show me the "Arghena" item in the `songlist` file, or is it the official one?
> 
> `DOWNLOAD_FORBID_WHEN_NO_ITEM` must work with the `songlist` file.

the funny thing is, Arghena isn't able to be downloaded when the songlist file exists in the right place in the server, whether the `DOWNLOAD_FORBID_WHEN_NO_ITEM` is set to TRUE or not. The existence of the songlist file itself just ruins somekind of the mechanism of downloading Arghena.

**Comment by Lost-MSth** [comment]
64526e3c4b6c439eca808ebd766941d6be3886bf fixed
