### ISSUE TITLE
Plans of adding the entire maps on the repo by default

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#178]
I would like to ask first if you currently, or in the near future have plans to add the maps that have same features with the official world mode. I know this would be difficult, and would need a lot of time or the modification of the client to somehow retrieve the world mode data.

The second thing to ask is, if you have any minds to use the maps that I'm currently working on when finished. 

https://github.com/rlarhsid/arcaea_map

This is the current thing I'm working on, my goal is to replicate all the maps (from chapter 1 ~ 8, beyond and breached). I can't specify the date that this work will be completely finished, but it could be good if the all of the maps are on the default repo, so people don't have to struggle finding or building the maps from scratch. This would be best to people who are focusing on trying to make the original server experience, which means not using `WORLD_SONG_FULL_UNLOCK` or etc.

Thanks for reading my long and boring report. I will wait for your responses.

**Comment by Lost-MSth** [comment]
I will not add world maps any more. When the repo begins, I added them casually. But now I find world maps, song data, bundle data or something else are customizable data. This repo is not just for simulating the official. So, the best way is to split data with the program, and I can give some test maps for reference.

Surely, if you want to create the repo full of official maps, that's good. Maybe I will mention it in the document.
