### ISSUE TITLE
I don't have VPS to connect with my other devices.

### ISSUE THREAD

**Issue by aliyafarhana** [Lost-MSth/Arcaea-server#179]
Is it possible to put many hosts? Because what I thought is I can put many hosts. So, I can connect to them. Also, is it possible I connect like this by using a VPN?

(Sorry, if my question is look so dumb and stupid. I'm not good at English).

Thank you!

**Comment by Lost-MSth** [comment]
Run one arcaea server on one VPS or one cloud server. Use some middleware like nginx setting on other servers to forward the connections. Also CDN can do so.

**Comment by aliyafarhana** [comment]
> Run one arcaea server on one VPS or one cloud server. Use some middleware like nginx setting on other servers to forward the connections. Also CDN can do so.

The reason I don't have VPS is I don't have money to buy it. And what's nginx? What do you mean forward the connections? And what's CDN? I'm sorry but I've never use this stuff in my life. I would like to know. How can I actually connect the server everywhere and everytime at anywhere and anytime without any VPS.

**Comment by Lost-MSth** [comment]
Emmm... If you don't want to pay any money, maybe the only way is some free FRP provider with your PC. Oh if your PC has one public IP, it is easier.

Well, I haven't understood what you want to do. I just guess you want to open the server on Internet.

**Comment by aliyafarhana** [comment]
> Emmm... If you don't want to pay any money, maybe the only way is some free FRP provider with your PC. Oh if your PC has one public IP, it is easier.
> 
> Well, I haven't understood what you want to do. I just guess you want to open the server on Internet.

Well, I want to connect to the private server without any VPS. So I want to know how to forwarding the connection and how to setup the public IP? Can you show me?

**Comment by Lost-MSth** [comment]
Public IP depends on your network provider. If you have no public IP, you need FRP to expose your host. Or you can use virtual LAN if the server's user is only you.

However, FRP normally has a limit. You can search for them on Google to learn more.

**Comment by aliyafarhana** [comment]
> Public IP depends on your network provider. If you have no public IP, you need FRP to expose your host. Or you can use virtual LAN if the server's user is only you.
> 
> However, FRP normally has a limit. You can search for them on Google to learn more.

Well, I play on 2 devices. So, I want to play with my mobile data, it is possible? Also, I want to try connect by using Termux. But, are proxy still needed?

**Comment by Lost-MSth** [comment]
I think it is possible. However, I am not sure about the actual effect.

You mean run the server on termux? That's ok. So what is the proxy?

**Comment by aliyafarhana** [comment]
Well, I usually connect to the server by using CMD and Charles (for PC) and Vproxid for Android. But I'm not sure for Termux, if it requires the proxy. Also, I've thinking if I was able to connect to the server by set up the host of my device hotspot, is it possible too? Because what I know is, the IP need to be the same.

**Comment by Lost-MSth** [comment]
Remote mapping is needed with the proxy application in your situation. I don't know why you mention hotspot. I think it has no relation with the server. Maybe you need to search for more information about computer network basic.
