### ISSUE TITLE
关于Arcaea3.6.0客户端的问题

### ISSUE THREAD

**Issue by AsukaMikoto** [Lost-MSth/Arcaea-server#18]
Arcaea更新到3.6.0之后
通过Charles请求时，发现会卡在一个Method为CONNECT的方法上
貌似这个Method的CONNECT的连接无法建立时，他下面的POST包也不发了
还有办法让arc连接到本地服务器吗

**Comment by Lost-MSth** [comment]
客户端加了证书校验，Charles证书会导致客户端拒绝连接 目前能想到的办法就是去binary文件里干掉ssl有关函数------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月14日(星期五) 上午10:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Lost-MSth/Arcaea-server] 关于Arcaea3.6.0客户端的问题 (#18)

**Comment by AsukaMikoto** [comment]
把ssl的函数都干掉就行了吧

**Comment by Lost-MSth** [comment]
是

**Comment by AsukaMikoto** [comment]
好 谢谢大佬

**Comment by Kaifeng666** [comment]
> 好 谢谢大佬

大佬，你是如何删除ssl函数的？

**Comment by Young-Lord** [comment]
> 大佬，你是如何删除ssl函数的？

同问

**Comment by Kaifeng666** [comment]
> > 大佬，你是如何删除ssl函数的？
> 
> 同问

会了，挺敏感的不好传播，和我一样从零开始学点逆向吧qwq

**Comment by Kaifeng666** [comment]
> > 会了，挺敏感的不好传播，和我一样从零开始学点逆向吧qwq
> 
> 我也会逆向的其实x 只是找不到验证的位置和硬编码的证书内容

多练(
