### ISSUE TITLE
About .ogg downloads other than base/3

### ISSUE THREAD

**Issue by CoreAndCrew** [Lost-MSth/Arcaea-server#181]
(using v2.11.3.13)

Is it possible to add downloadable audio files other than base/3.ogg (eg 0.ogg / 1.ogg / 4.ogg) when dealing with audioOverride? I know that using audioOverride on other difficulties (meaning PST/PRS) is possible offline, but it seems that attempting to play a song with other diffs having audioOverride after download leads to those charts crashing. I tried adding the extra oggs in FILE_NAMES from download.py but that seems to break downloads entirely. Any help with this? Thank you!

**Comment by Lost-MSth** [comment]
Sorry but impossible. The client only accepts `3.ogg` and `base.ogg` these two audio files from the server, which is hard-coded.

**Comment by CoreAndCrew** [comment]
Aw that sucks, thanks for answering tho!
