### ISSUE TITLE
Some functions not imported yet

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#186]
**Environment**
Server: Windows 10
Client: 5.10.4 Global / Android

**Problem**
https://github.com/Lost-MSth/Arcaea-server/issues/164
Well, it seems like some features that I had mentioned at there is not fully implemented yet.
<img width="815" alt="image" src="https://github.com/user-attachments/assets/c04637f4-b6f0-4360-920d-eac126e32932">
The function that I talked about at the first function (About Fatalis Hikari and Testify) seems to be perfectly fixed.
However, the second function that I've talked about, which is about the death / disappearance of Tairitsu, isn't implemented yet.
https://youtu.be/9bTMqi8Vwo8?t=1216
You could try watching this video, I don't have good english skills to say this clearly. The Tairitsu character is gone, and all the other collaboration Tairitsu's names are glitched.
By reading the server log, I assume that when the client sends the `finale_start` request, the server gives the user character 55 (Fatalis Hikari).
If it's possible, I think that adding a code to the server to somehow replicate the video's anomaly will solve this issue.
I guess this probably might be hardcoded, so tell me if this function is not able to replicate.

**Comment by Lost-MSth** [comment]
Emm... Not deleting Tairitsu in finale challenge is what I intentionally designed. Do you think this has affected the finale story?

In theory, this feature can be added. Let me consider about it, and maybe I will implement it later when I have more free time.

**Comment by rlarhsid** [comment]
It doesn't directly affect something to the game functions or etc, but I just suggested this as adding this feature could replicate the original server's finale challenge a bit more accurately, thus giving an immersive experience to the user.

It's good to hear that you'll consider of adding this or not. If this is more like a bothersome and complicated feature (if you think so), it'll also be okay of not adding this (because like I said, it doesn't directly affect something).
