### ISSUE TITLE
Score calculation bug on latest linkplay server

### ISSUE THREAD

**Issue by rlarhsid** [Lost-MSth/Arcaea-server#187]
**Describe the bug 问题描述**
Same as the title. The linkplay server sends a mysterious score, which I can't assume where it came from. The game score pops up even when the game isn't even finished yet.

**To Reproduce 复现过程**
1. Set up the server by using the latest repo, and make sure the linkplay server is set as standalone
2. Play a linkplay game
3. After a few games played, the gameplay will break, like the video I attached.

**Error log 报错日志**
No error logs, but there's a weird terminal screenshot.

**Screenshots 截图**
![image](https://github.com/user-attachments/assets/362317e2-5846-48bf-956b-95ea878acb4c)
Score 0 with 1468 Shiny Perfect, 66536 Healthy. 

**Environment 环境**
 - Server OS: Windows 11
 - Client OS: Android 14
 - Server Version: dev branch 2.12.0
 - Client Version 5.10.4 / bundle 5.10.5

**Comment by rlarhsid** [comment]
https://github.com/user-attachments/assets/7fe00209-2f4e-4c4b-80b4-b3336837b76a

yea this is the bug im talking about

**Comment by Lost-MSth** [comment]
Checked. I am not sure if it is fixed or not in a6c26dedfe6be50e2b9268cb2cb0d90c1cbe6ce9.

**Comment by rlarhsid** [comment]
> Checked. I am not sure if it is fixed or not in [a6c26de](https://github.com/Lost-MSth/Arcaea-server/commit/a6c26dedfe6be50e2b9268cb2cb0d90c1cbe6ce9).

It seems like that this issue is solved, I tested by my devices for a couple times and didn't happen anymore. Thanks for fixing this issue!
