### ISSUE TITLE
下載歌曲時提示發生錯誤

### ISSUE THREAD

**Issue by c8763yee** [Lost-MSth/Arcaea-server#19]
### 環境
- Windows 10 20H2 64bit
- iOS 14.5.1
- 修改過binary的Arcaea 3.5.3
- Python 3.9.1
- Arcaea-server 2.4

### 問題
其他部份沒有問題，但當我試著下載任一歌曲時提示
> 下載曲目時發生錯誤， 請重試。

當我把`DOWNLOAD_LINK_PREFIX`的內容改為[http://<HOST:PORT>/latte/13/serve/download/]時會卡在0%一段時間後出現錯誤訊息，而留空時會直接提示錯誤(100%複現)

### songs資料夾配置
- songs
- - \<songid\>
- - - 0.aff
- - - 1.aff
- - - 2.aff
- - - 3.aff
- - - base.ogg
-----------------------------------
#### Request
> http://<<HOST:PORT>>/latte/13/serve/download/me/song?sid=aleph0&url=true

#### Respond
```{
	"success": true,
	"value": {
		"aleph0": {
			"audio": {
				"checksum": "fe6ae6e6e0141029e71a4752c876908d",
				"url": "https://<<HOST:PORT>>/download/aleph0/base.ogg?t=1ab990e9864edd8649fc73cbb0e4fcb4"
			},
			"chart": {
				"0": {
					"checksum": "b01fe9a05fb57227c0f1f26379d18940",
					"url": "https://<<HOST:PORT>>/download/aleph0/0.aff?t=3a77970020b6943538dcebf70af245ba"
				},
				"1": {
					"checksum": "2ac52e32ba7dad35e3cd2fe2f7fd36ed",
					"url": "https://<<HOST:PORT>>/download/aleph0/1.aff?t=621d486ee175555ff98252b9ef443546"
				},
				"2": {
					"checksum": "10d73f674aaf5cb1c69a534bb0a2f673",
					"url": "https://<<HOST:PORT>>/download/aleph0/2.aff?t=6a37359b5b2dff8878727e4585e0e633"
				},
				"3": {
					"checksum": "10d73f674aaf5cb1c69a534bb0a2f673",
					"url": "https://<<HOST:PORT>>/download/aleph0/3.aff?t=26c7dfc6568d82fa86a4c3445ac993aa"
				}
			}
		}
	}
}
```

**Comment by Lost-MSth** [comment]
DOWNLOAD_LINK_PREFIX应该是https host port download，没有latte/13才对 注意到了您的抓包信息，里面的返回的url是对的，但是是https连接(请求时却是http)，猜测您在外层套了反代？ ios必定要求https，DOWNLOAD_LINK_PREFIX就是为了修改http为https，但为什么抓包信息中的url已经是https了，有点奇怪 猜测问题可能出在https上，直接访问下载连接试试，如果确实https的下载连接可以连通，且服务器返回的是https的下载连接，应该是没有问题的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月15日(星期六) 晚上7:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Lost-MSth/Arcaea-server] 下載歌曲時提示發生錯誤 (#19)

**Comment by c8763yee** [comment]
直接訪問時會出現回應時間過長

-----------------------------------------
> DOWNLOAD_LINK_PREFIX应该是https host port download，没有latte/13才对 注意到了您的抓包信息，里面的返回的url是对的，但是是https连接(请求时却是http)，猜测您在外层套了反代？ ios必定要求https，DOWNLOAD_LINK_PREFIX就是为了修改http为https，但为什么抓包信息中的url已经是https了

其實都是走https

**Comment by Lost-MSth** [comment]
呃呃？怎么会这样呢，GET请求也会405？唔，https是中间件开的吗，配置应该没问题吧
下载链接应该保证能直接访问到

**Comment by c8763yee** [comment]
`DOWNLOAD_LINK_PREFIX`改成 https://HOST:PORT/download/ 之後可以直接訪問了，不過遊戲內下載還是提示錯誤

**Comment by Lost-MSth** [comment]
emmmmm，再抓下包ios的下载请求包看看返回的下载链接是否正确？如果正确的话，我也不知道了啊啊啊啊，就看看服务器日志有没有请求下载的，证书有没有过期之类的

**Comment by c8763yee** [comment]
好吧，感謝大佬願意花時間幫我解決問題

**Comment by Kaifeng666** [comment]
> 好吧，感謝大佬願意花時間幫我解決問題
> 
> Well, thanks for taking the time to help me out

请问大佬手机端要进行什么操作才可以，我用v2ray代理了arc，但是arc莫得任何变化，歌曲也全锁着在
