### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by TechnoHT** [Lost-MSth/Arcaea-server#20]
Windows 10 20H2 x64
Android 9 (rev 4.9 kernel)
Arcaea 3.6.1c
Python 3.9.1
Arcaea-server 2.4

Can't connect to the local server whether or not I have enabled redirect or try to set up a proxy
is there any workaround to connect properly ?

**Comment by yuuuuue** [comment]
\

> Windows 10 20H2 x64
> Android 9 (rev 4.9 kernel)
> Arcaea 3.6.1c
> Python 3.9.1
> Arcaea-server 2.4
> 
> Can't connect to the local server whether or not I have enabled redirect or try to set up a proxy
> is there any workaround to connect properly ?

I think you should use ida to crack the certificate check of the arcaea 3.6.1c client,so it can be connected to the local server

**Comment by Lost-MSth** [comment]
3.6.1?? Oh maybe you forget to kill SSL certificate verification in cilent.
You know lowiro has updated their safety measures since 3.6.0, including SSL certificate verification of cilent.
I suggest that you should kill all functions about ssl in binary file of Arcaea and use a proxy app to link Charles.
And maybe 3.6.0 is a better choice because ...emmm.. you will know the reason soon.

Wait? Someone replied before I did...

**Comment by TechnoHT** [comment]
Oh thanks : D, I didn't go through the SSL-verity removal in 3.6.1 client ( Since I'm no expert and there is no tutorial so I have to figure out myself :p )

**Comment by yuuuuue** [comment]
> Oh thanks : D, I didn't go through the SSL-verity removal in 3.6.1 client ( Since I'm no expert and there is no tutorial so I have to figure out myself :p )

i can help you, just give me your discord username :)

**Comment by TechnoHT** [comment]
> i can help you, just give me your discord username :)

My Discord is TechnoHT#7421, Really appreciate for helping me ^^

**Comment by TechnoHT** [comment]
Solved ( by using 3.5.3c lol : D, 3.6.0c dl ded )

Close

**Comment by rlarhsid** [comment]
> > Oh thanks : D, I didn't go through the SSL-verity removal in 3.6.1 client ( Since I'm no expert and there is no tutorial so I have to figure out myself :p )
> 
> i can help you, just give me your discord username :)

I'm really sorry to mention you, could you please help me if you can?
