### ISSUE TITLE
《纯萌新如何逼疯开发者》

### ISSUE THREAD

**Issue by Kaifeng666** [Lost-MSth/Arcaea-server#21]
教一下怎么搭建这个服务器...安卓11折腾了半天了，说明文档和指示在哪没看见在哪啊...

**Comment by Kaifeng666** [comment]
![%1$Q_D07EIKQ) F DA`N8%I](https://user-images.githubusercontent.com/56071624/121483079-5cc29980-ca00-11eb-8ed0-015de962aa92.png)
这样不正常吧》。..

**Comment by Lost-MSth** [comment]
请求不合规，可能是https请求发到了http上导致的，不知道你干了什么------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月10日(星期四) 下午3:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Lost-MSth/Arcaea-server] 如何使用啊... (#21)

**Comment by Kaifeng666** [comment]
现在OK了，再就是看怎么操作手机上的东西了.....




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lost-MSth/Arcaea-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lost-MSth/Arcaea-server] 如何使用啊... (#21)





 请求不合规，可能是https请求发到了http上导致的，不知道你干了什么------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年6月10日(星期四) 下午3:28 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Lost-MSth/Arcaea-server] 如何使用啊... (#21)

**Comment by Kaifeng666** [comment]
服务器搭好了，但是就是手机arc访问不了这个本地服务器，用的还是官方的...

版本是3.5.1c的，文档里说的用Charles引导arc去访问本地服务器我不知道要怎么操作

手机WiFi也设置了代理

**Comment by Lost-MSth** [comment]
3.5.1应该没啥问题，按照操作还是比较简单的吧，不知道你证书设置有没有设置正确，确保抓到包应该就可以转发了
也可以参考baidu

**Comment by MBRjun** [comment]
我的手机Arcaea安装版本为3.5.2c（为了同时使用原版改了包名）
手机浏览器打开arcapi.lowiro.com正常解析到电脑
但是Arcaea似乎不认hosts直接用官方

**Comment by Lost-MSth** [comment]
能抓到包吗，看起来你解析成功了，可能是证书问题，也可能只需要重新开一下客户端就好了
等一下，你是改手机hosts的？那我不太清楚，dns解析我就没成功过，盲猜ssl pinning

**Comment by MBRjun** [comment]
手机Ping/浏览器访问都能指向电脑，但是游戏内连接至官服
请问大佬是用什么方法转发的请求？（

**Comment by Lost-MSth** [comment]
依赖那边写着的……
连到官服应该是SSL证书问题，然后变成socket连接了？我不清楚，真没试过（）

**Comment by Kaifeng666** [comment]
> 3.5.1应该没啥问题，按照操作还是比较简单的吧，不知道你证书设置有没有设置正确，确保抓到包应该就可以转发了
> 也可以参考baidu

证书好像没设置。。不知道要怎么设置 : (

**Comment by Lost-MSth** [comment]
问baidu也行，我写的挺清楚的吧（
直接搜怎么HTTPS抓包就能找到相关教程

**Comment by Kaifeng666** [comment]
哦，淦，看了下之前解决的issues，发现只有我一个人是心血来潮啥都不会的萌新，抓包什么的我也不知道抓了什么些鬼东西qwq
![image](https://user-images.githubusercontent.com/56071624/122795686-26cec080-d2f0-11eb-9bb1-373af740fa82.png)
这是我把手机上所有WiFi权限关了，只保留arcaea后抓的包，进入游戏到爬了个梯结算，不知道什么东西该留下来有用...

**Comment by Kaifeng666** [comment]
你们说的数据库和后台又是什么东西qwq
![image](https://user-images.githubusercontent.com/56071624/122796051-8e850b80-d2f0-11eb-89da-de5f270ba18e.png)
![image](https://user-images.githubusercontent.com/56071624/122796078-95138300-d2f0-11eb-833e-c9b4262815d9.png)
是这个吗?

**Comment by Lost-MSth** [comment]
你把我弄傻了（）
不知道你在干什么
emmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
这种基础的环境搭建问题，您应该尝试找一下教程的（我怎么记得我发过邮件给你啊，那里面提了教程的啊啊啊啊啊啊

**Comment by Kaifeng666** [comment]
**《论如何逼疯开发者》**，就是不知道该干什么，找什么的教程呐qwq，邮件没有说教程

**Comment by Kaifeng666** [comment]
莫西莫西，大佬还在吗qwq

**Comment by Lost-MSth** [comment]
wiki plz

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122798517-44515980-d2f3-11eb-812d-0d7c9a31610a.png)
阿巴阿巴阿巴

**Comment by Lost-MSth** [comment]
咳，请开动你的小脑筋可好（）
> 空白不是空白

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122801273-7ca66700-d2f6-11eb-819c-3129660467f5.png)
这个吗....

**Comment by Lost-MSth** [comment]
是的（顺便等会就删了这条和上一条评论）

**Comment by Kaifeng666** [comment]
草，问题就是我直接看不懂这些东西，也不知道找哪些教程(废人啊这是

**Comment by Lost-MSth** [comment]
草，那几乎是手把手了吧啊吧啊吧(

**Comment by Kaifeng666** [comment]
自信点，把几乎去掉XD
要不大佬我直接交学费吧qwq

**Comment by Lost-MSth** [comment]
别啊，有些四年级小朋友都会的()
请您加油

**Comment by Kaifeng666** [comment]
你说的四年级小朋友是哪个，我这就去请教他qwq


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lost-MSth/Arcaea-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 凌晨1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lost-MSth/Arcaea-server] 《纯萌新如何逼疯开发者》 (#21)





 
别啊，有些四年级小朋友都会的()
 请您加油

**Comment by Lost-MSth** [comment]
至少有两位，自己找吧()
而且是她不是他

**Comment by MBRjun** [comment]
> ![image](https://user-images.githubusercontent.com/56071624/122798517-44515980-d2f3-11eb-812d-0d7c9a31610a.png)
> 阿巴阿巴阿巴

这个是因为Github在中国大陆受到了审查。。。我现在不挂梯子都上不去Github

**Comment by Kaifeng666** [comment]
好

**Comment by MBRjun** [comment]
我邮箱绑定了Github原来这就是我手机一直响的原因（

**Comment by Kaifeng666** [comment]
> 我邮箱绑定了Github原来这就是我手机一直响的原因（

对不住，打扰大佬了😂

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122850507-ea2ab580-d33f-11eb-9f34-842d231e7a9f.png)
大佬们，这样算是成功了嘛...但是进游戏没变化，版本是3.5.3c愚人节的，我电脑上的Charles需要调什么东西吗....

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122850659-337b0500-d340-11eb-9495-1f20312c6231.png)

大佬们，这样算是成功了嘛...但是进游戏没变化，版本是3.5.3c愚人节的，我电脑上的Charles需要调什么东西吗....

**Comment by MBRjun** [comment]
一样
改的Hosts？ Hosts对游戏无效 使用其他代理/转发

**Comment by Kaifeng666** [comment]
> 一样
> 改的Hosts？ Hosts对游戏无效 使用其他代理/转发

大佬你是用什么代理的

**Comment by Kaifeng666** [comment]
> 一样
> 改的Hosts？ Hosts对游戏无效 使用其他代理/转发

哦，淦，搞了半天游戏还是不鸟代理...我得用Charles干些啥吗

**Comment by Kaifeng666** [comment]
我离成功应该就差这一步了...
![image](https://user-images.githubusercontent.com/56071624/122859635-e5b9c900-d34e-11eb-8b4c-c7304a021038.png)

**Comment by Kaifeng666** [comment]
我试着用v2ray,然后发现我怎么调设置都不管用
![image](https://user-images.githubusercontent.com/56071624/122870437-400f5580-d360-11eb-95b0-a0d5eca07ef7.png)
命令行就跳这些
![image](https://user-images.githubusercontent.com/56071624/122870492-4e5d7180-d360-11eb-97a8-f98cc4c2c6f6.png)

**Comment by Lost-MSth** [comment]
400，有可能是https转发到http上的报错

**Comment by Kaifeng666** [comment]
不会弄了，不知道问题出在哪。。不知道是不是setting的问题
![image](https://user-images.githubusercontent.com/56071624/122876113-b06da500-d367-11eb-88a0-37a6bf7ec10e.png)

**Comment by Kaifeng666** [comment]
> 不会弄了，不知道问题出在哪。。不知道是不是setting的问题
> ![image](https://user-images.githubusercontent.com/56071624/122876113-b06da500-d367-11eb-88a0-37a6bf7ec10e.png)

好家伙，直接变成404了

**Comment by Lost-MSth** [comment]
不是，转发的问题罢了，我不知道v2ray能不能成功，毕竟没有试过（）

**Comment by Kaifeng666** [comment]
大佬你们用什么转发的，我这v2ray我已经试了一个上午了qwq

**Comment by Lost-MSth** [comment]
写在readme里面了啊（）

**Comment by Kaifeng666** [comment]
请问大佬用的哪个功能..远程映射还是端口转发还是别的什么qwq(拿到软件不会用

**Comment by Lost-MSth** [comment]
。。。。。map remote

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122885352-9769f180-d371-11eb-899b-0decd8498682.png)
![image](https://user-images.githubusercontent.com/56071624/122885552-c3857280-d371-11eb-90ae-307a49612031.png)

打咩达内~

**Comment by Lost-MSth** [comment]
抓包信息呢，这连到哪去了？

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122886378-7e157500-d372-11eb-9822-ec19e8152f3a.png)
![image](https://user-images.githubusercontent.com/56071624/122886445-8d94be00-d372-11eb-9fbe-20100bd8a46c.png)
![image](https://user-images.githubusercontent.com/56071624/122886463-92597200-d372-11eb-9c3f-60a6c63318c6.png)

**Comment by Lost-MSth** [comment]
你看下错误信息啊，八成证书没装()

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122892860-5aedc400-d378-11eb-898d-50142cf75dcf.png)
![image](https://user-images.githubusercontent.com/56071624/122892865-5c1ef100-d378-11eb-8ffd-1e530d090861.png)
emmmm，手机和电脑都安的一个证书，不知道怎么回事...
![image](https://user-images.githubusercontent.com/56071624/122892960-73f67500-d378-11eb-8880-4ed5c022c550.png)

**Comment by Lost-MSth** [comment]
ssl那边写*:*就行
安卓7以上有额外步骤，教程里写了()

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122894407-bbc9cc00-d379-11eb-8ff6-d9704edb025d.png)
这样吗

**Comment by Lost-MSth** [comment]
大概()

**Comment by Kaifeng666** [comment]
G了，得解锁system分区，安卓11好像还不能qwq

**Comment by MBRjun** [comment]
什么设备

**Comment by Kaifeng666** [comment]
> 什么设备

米10s

**Comment by MBRjun** [comment]
米10S解锁后可以将system挂载为rw

**Comment by YorokobiMaster** [comment]
11理论能解锁system分区吧，twrp都有了

**Comment by yuuuuue** [comment]
hmm i think we just need to change the sdk to 22 instead of 29 or 30,and the cert will work without root

**Comment by MBRjun** [comment]
> hmm i think we just need to change the sdk to 22 instead of 29 or 30,and the cert will work without root

降低安卓版本不现实 SDK22得安卓5了吧（？

**Comment by yuuuuue** [comment]
> > hmm i think we just need to change the sdk to 22 instead of 29 or 30,and the cert will work without root
> 
> 降低安卓版本不现实 SDK22得安卓5了吧（？

sounds like unrealistic but at least it worked

**Comment by yuuuuue** [comment]
just use apk editor

**Comment by Kaifeng666** [comment]
> 米10S解锁后可以将system挂载为rw

什么操作那是qwq

**Comment by yuuuuue** [comment]
> > 米10S解锁后可以将system挂载为rw
> 
> 什么操作那是qwq

bootloader unlock 

must unlock the bootloader in order to root device

**Comment by YorokobiMaster** [comment]
话说各位，iOS设备怎么办，只能越狱装魔改ipa了吗？

**Comment by MBRjun** [comment]
> > 米10S解锁后可以将system挂载为rw
> 
> 什么操作那是qwq

将系统分区挂载为可读写
操作需要解锁
在解锁之前，请使用备份功能备份至OTG/电脑
解锁会清除全部数据

**Comment by MBRjun** [comment]
> 话说各位，iOS设备怎么办，只能越狱装魔改ipa了吗？

自己魔改IPA吧 最好有一台Mac设备
越狱可能会更方便

**Comment by Lost-MSth** [comment]
> 话说各位，iOS设备怎么办，只能越狱装魔改ipa了吗？

ios比安卓简单)

**Comment by Kaifeng666** [comment]
突然就变成了群聊qwq

**Comment by MBRjun** [comment]
> 突然就变成了群聊qwq

Github群（确信）

**Comment by YorokobiMaster** [comment]
求给iOS指个路(
616这一更3.6，什么都不知道了，老方法全部木大(

**Comment by MBRjun** [comment]
> 求给iOS指个路(
> 616这一更3.6，什么都不知道了，老方法全部木大(

我有一台iOS设备和一台Mac 但是不太会改iOS的（

**Comment by Lost-MSth** [comment]
3.6？我也不清楚，问暗影去()

**Comment by MBRjun** [comment]
> 3.6？我也不清楚，问暗影去()

暗影只有B站有号吗（

**Comment by Lost-MSth** [comment]
我没有设备测试ios，所以根本没法搞，ios闪退都很正常)

**Comment by yuuuuue** [comment]
这已经成为github上的一个学习小组

**Comment by Lost-MSth** [comment]
> > 3.6？我也不清楚，问暗影去()
> 
> 暗影只有B站有号吗（

其它联系方式不清楚
(实际上他也会看issue的吧，可以蹲一蹲)

**Comment by TechnoHT** [comment]
can we put this into a GitHub *Discussion* instead of issue

**Comment by YorokobiMaster** [comment]
草

**Comment by yuuuuue** [comment]
lol

**Comment by YorokobiMaster** [comment]
为什么不呢（

**Comment by MBRjun** [comment]
> can we put this into a GitHub _Discussion_ instead of issue

没玩过，How 2 do it（

**Comment by yuuuuue** [comment]
> 没玩过，How 2 do it（

tell lost

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122903906-6e059180-d382-11eb-83cb-36b21540a786.png)
麻了

**Comment by MBRjun** [comment]
!(  )[https://cos.mbrjun.cn/IMGS/2021/06/22/l.jpg]
快要打骨折了

**Comment by MBRjun** [comment]
（MarkDown怎么引用图片来着

**Comment by MBRjun** [comment]
> ![image](https://user-images.githubusercontent.com/56071624/122903906-6e059180-d382-11eb-83cb-36b21540a786.png)
> 麻了

输入“su”，/system会被自动挂载为可读写（

**Comment by YorokobiMaster** [comment]
我寻思着
为啥不刷magisk

**Comment by YorokobiMaster** [comment]
刷个magisk多舒服，手机直接操作

**Comment by MBRjun** [comment]
他机子bl还没解吧（？

**Comment by Kaifeng666** [comment]
> 我寻思着
> 为啥不刷magisk

有面具有root

**Comment by MBRjun** [comment]
MIUI是真的难用

**Comment by YorokobiMaster** [comment]
有面具你不早说啊喂（

**Comment by MBRjun** [comment]
> > 我寻思着
> > 为啥不刷magisk
> 
> 有面具有root

输完su那就已经是读写了，直接操作

**Comment by Kaifeng666** [comment]
有面具怎么解锁，秋梨膏

> 有面具你不早说啊喂（

**Comment by MBRjun** [comment]
> 有面具怎么解锁，秋梨膏
> 
> > 有面具你不早说啊喂（

？你没解锁刷面具？

**Comment by yuuuuue** [comment]
> MIUI是真的难用

我同意

**Comment by Kaifeng666** [comment]
输了su，mt管理器去操作还是显示读写失败

**Comment by YorokobiMaster** [comment]
不是，刷了面具，system分区不就应该也会解锁吗，，，

**Comment by Kaifeng666** [comment]
> > 有面具怎么解锁，秋梨膏
> > > 有面具你不早说啊喂（
> 
> ？你没解锁刷面具？

我说的解锁system

**Comment by TechnoHT** [comment]
> > can we put this into a GitHub _Discussion_ instead of issue
> 
> 没玩过，How 2 do it（

go to Repository Settings
scroll down a bit you will see "Discussion" is unticked ( need access to the repo 1st )

**Comment by MBRjun** [comment]
> 输了su，mt管理器去操作还是显示读写失败

（Read Only File System Error？）

**Comment by Kaifeng666** [comment]
> 不是，刷了面具，system分区不就应该也会解锁吗

难不成要换个文件管理器

**Comment by yuuuuue** [comment]
> > > can we put this into a GitHub _Discussion_ instead of issue
> > 
> > 
> > 没玩过，How 2 do it（
> 
> go to Repository Settings
> scroll down a bit you will see "Discussion" is unticked ( need access to the repo 1st )

only the owner can do it

**Comment by MBRjun** [comment]
> > 不是，刷了面具，system分区不就应该也会解锁吗
> 
> 难不成要换个文件管理器

我MT管理器能操作system，实在不行twrp下（

**Comment by Kaifeng666** [comment]
> > > 不是，刷了面具，system分区不就应该也会解锁吗
> > 
> > 
> > 难不成要换个文件管理器
> 
> 我MT管理器能操作system，实在不行twrp下（

这机子没twrp，惊不惊喜

**Comment by MBRjun** [comment]
> > > > 不是，刷了面具，system分区不就应该也会解锁吗
> > > 
> > > 
> > > 难不成要换个文件管理器
> > 
> > 
> > 我MT管理器能操作system，实在不行twrp下（
> 
> 这机子没twrp，惊不惊喜

机子设备代号给下我找找
（真没有也没啥救 我记得有小米专门解锁/system的工具

**Comment by Kaifeng666** [comment]
![image](https://user-images.githubusercontent.com/56071624/122904861-4f53ca80-d383-11eb-83e5-a13afc49c196.png)
KUSO！

**Comment by yuuuuue** [comment]
请注意，只要使用低于v3.6.0的版本，就必须将GAME_API_PREFIX改为/latte/13而不是/blockchain/14。
