### ISSUE TITLE
「Lets talk about how to make the coder crazy.」

### ISSUE THREAD

**Issue by Adsicmes** [Lost-MSth/Arcaea-server#27]
![image](https://user-images.githubusercontent.com/79645438/127773874-667501f3-2462-4d27-a75c-760448768483.png)

**Comment by Adsicmes** [comment]
Charles相关文档没有（

**Comment by Lost-MSth** [comment]
嗯，没有，下一个（）
> 睁大眼睛，哦不，应该是open your mind

**Comment by Adsicmes** [comment]
不会用Charles咋办

**Comment by Lost-MSth** [comment]
你可以选择baidu bing google
你也可以仔细找找文档在哪（）
你甚至可以凭借硬实力自己捣鼓出来
更有甚者换个思路也行，charles不是必须的

**Comment by Adsicmes** [comment]
哦对不起我会了（（（
稍微学了一下（（（（（（（

非常抱歉！！！！！！
