### ISSUE TITLE
为iOS和iPadOS开放TestFlight或IPA包安装

### ISSUE THREAD

**Issue by cheny0y0** [Lost-MSth/Arcaea-server#29]
README文件里面只有APK包,只能给Android设备用。。

**Comment by Lost-MSth** [comment]
啊？没懂，konmai下载站也木大了，安卓现在也要自己到官网下载吧
ios的IPA文件可以自己拆的，可能需要越狱我也不太清楚，找各种群说不定有（）

**Comment by MBRjun** [comment]
IPA可以提取，但是我的苹果本坏了...
