### ISSUE TITLE
/coffee/12/compose/aggregate应该是批量请求的接口

### ISSUE THREAD

**Issue by 603185423** [Lost-MSth/Arcaea-server#3]
`每个call中的endpoint都应该是一条'/coffee/12'+call[i]['endpoint']的请求
官方那边是一条URL塞超过6个子请求就直接封号，所以id应该不会>5
然后是返回

{
    "success": true,
    "value": [
        {"id": 0, "value": {response0}},
        {"id": 1, "value": {response1}},
        {"id": 2, "value": {response2}},
        {...}
    ]
}

语文不好，可能表述不是很清楚(

**Comment by Lost-MSth** [comment]
啊这，emm我大致知道那应该是多个请求拼的，但事实上我只见过两种，就是0和0~5，所以直接就if完事了，处理得有点挫哈

**Comment by 603185423** [comment]
主要是想用botarcapi查分数(
要改的话是不是每个函数都要改
是的话我就选择去改botarcapi的代码了
吊死。jpg(

**Comment by Lost-MSth** [comment]
草？用/compose/aggregate能查的只有一首recent吧，具体来说怎么查？

**Comment by 603185423** [comment]
http://xxx/coffee/12/compose/aggregate?calls=[{"endpoint":"/score/song/friend?song_id=tempestissimo&difficulty=3&start=0&limit=1","id":0},{"endpoint":"/score/song/friend?song_id=grievouslady&difficulty=2&start=0&limit=1","id":1},{"endpoint":"/score/song/friend?song_id=fractureray&difficulty=2&start=0&limit=1","id":2},{"endpoint":"/score/song/friend?song_id=saikyostronger&difficulty=2&start=0&limit=1","id":3},{"endpoint":"/score/song/friend?song_id=axiumcrisis&difficulty=2&start=0&limit=1","id":4}]

**Comment by 603185423** [comment]
所以查b30就要把每首歌的每个难度都请求一遍
满离谱的(

**Comment by 603185423** [comment]
然后查分器还有一个单独请求/coffee/12/user/me
不过这个已经改完了(指查分器)

**Comment by Lost-MSth** [comment]
啊原来如此还有这种操作我这就去爬（
我根本没有发现啊

**Comment by Lost-MSth** [comment]
我试着改一下吧（哭）

**Comment by 603185423** [comment]
其实问题也不大
查一首歌的best用score/song/friend能查到
改一下查分器就行了
感觉改arcserver挺麻烦的(

**Comment by Lost-MSth** [comment]
好
其实主要是我太菜了（）
616骚操作真多啊喂

**Comment by TheSnowfield** [comment]
> 主要是想用botarcapi查分数(
> 要改的话是不是每个函数都要改
> 是的话我就选择去改botarcapi的代码了
> 吊死。jpg(

我也快看不懂自己的代碼了, 從JavaScript硬改過來的. 大量使用any去繞過編譯器檢查. 🤣

**Comment by TheSnowfield** [comment]
> 主要是想用botarcapi查分数(
> 要改的话是不是每个函数都要改
> 是的话我就选择去改botarcapi的代码了
> 吊死。jpg(

應該很好改, 但查詢的速度會慢非常多. 畢竟aggregate一次可以請求5個嘛.
Best30不是全部歌曲都查一次, 而是根據定數表内所有歌曲的定數從高到低查, 直到結果小於用戶ptt-2結束.
