### ISSUE TITLE
设置全解锁搭档后，会出现无法登录的问题

### ISSUE THREAD

**Issue by OasisAkari** [Lost-MSth/Arcaea-server#30]
CHARACTER_FULL_UNLOCK设置为True后，登录时自动添加的搭档等级恒为`None`，导致需要利用搭档等级计算数值的函数出错，导致无法登录
（如 https://github.com/Lost-MSth/Arcaea-server/blob/master/latest%20version/server/character.py#L114）
![image](https://user-images.githubusercontent.com/31803608/134913418-0e253a29-6a21-4082-a0d1-aee2ebc8775c.png)

**Comment by Lost-MSth** [comment]
可能是从旧版本更新过来导致的一个bug，数据库里的character表里max_level为空，或者是user_char_full表level为空，原因是前者需要手动加上等级，原因是后者……后台刷一下数据库（上传当前数据库文件就可吧）

某个版本完善世界模式改数据库结构的锅（）

**Comment by OasisAkari** [comment]
大概看了一下，似乎是上传数据库之后，会把新老数据库里的都有的角色各种数值信息全部变为空

**Comment by Lost-MSth** [comment]
emm好早之前的版本更新过来就会这样，属性名不一样导致的，小问题懒得管（bushi）

**Comment by OasisAkari** [comment]
那好吧）
