### ISSUE TITLE
注册接口返回308

### ISSUE THREAD

**Issue by Young-Lord** [Lost-MSth/Arcaea-server#32]
https://github.com/Lost-MSth/Arcaea-server/blob/d0be49fe20babb6fbce9a7dafbcc09b73f0f2dc4/latest%20version/main.py#L217
RT，版本3.9.1c，注册时客户端请求的是'/user'（没有斜杠）
![输出截图](https://user-images.githubusercontent.com/51789698/142748347-96079d19-805f-442e-9d75-8f177567f867.jpg)

**Comment by Lost-MSth** [comment]
xs，616改了，之前有杠（）
