### ISSUE TITLE
无法添加歌曲

### ISSUE THREAD

**Issue by zxhzxhz** [Lost-MSth/Arcaea-server#36]
arcaea version:3.5.5(ios)
server: v2.8
数据库arcsong：
![数据库arcsong](https://i.imgur.com/j942GOo.png)
文件：
![文件](https://i.imgur.com/XQGuveB.png)

然后这曲子并没有出现在游戏里，请问还需要动什么地方？

**Comment by Lost-MSth** [comment]
……
歌曲数据在客户端，请修改songlist，然后把曲绘和预览丢进songs
服务端仅需要0&1&2.aff和base.ogg

**Comment by zxhzxhz** [comment]
😂
原来如此
我还以为songlist是由服务器下发的
明白了
