### ISSUE TITLE
注册时默认源点从 114514 改为 0

### ISSUE THREAD

**Issue by JoinChang** [Lost-MSth/Arcaea-server#4]

**Comment by JoinChang** [comment]
且网页端修改全部用户的源点提示无修改。

**Comment by Lost-MSth** [comment]
注册memory变为0是因为以前的数量是写死的，现在数据库加了一条属性，数据同步的时候被留空导致为0
网页端我刚刚又试了一遍，可以用啊，你确定使用的是edit all the users 并且填了memory数量吗？

**Comment by JoinChang** [comment]
是

**Comment by JoinChang** [comment]
https://github.com/Lost-MSth/Arcaea-server/blob/dfcbb6f9c0d5299fdb3e3dfb4e7c5c8d687bc374/latest%20version/server/auth.py#L85

**Comment by Lost-MSth** [comment]
啊这，其实我这里曲目购买的本意不是限制用户打歌啦，只是不想浪费掉购买系统，走个形式性的购买（
或者还有个用途就是设置一些奇怪的购买数字之类的
这个memory数量也可以和官服拉开区别

emm 改一下也无所谓，我知道了
