### ISSUE TITLE
Cannot connect the client to localhost

### ISSUE THREAD

**Issue by skyventuree** [Lost-MSth/Arcaea-server#42]
I couldn't get the game to connect to the client, got an `EOF during handshake` on `CONNECT` method.
<img width="1408" alt="Screen Shot 2022-03-08 at 15 08 03" src="https://user-images.githubusercontent.com/34794115/157193781-a29a666c-af30-4310-a7a2-cda441bf2037.png">

**Comment by Lost-MSth** [comment]
#20
This may be helpful.
