### ISSUE TITLE
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by Tsuziku** [Lost-MSth/Arcaea-server#43]
![eee](https://user-images.githubusercontent.com/101255275/157425268-2fcfd879-2396-415a-8c29-f6b584ad1708.png)

**Comment by Lost-MSth** [comment]
Have you changed the `setting.py`? There is an `GAME_API_PREFIX` option.

**Comment by Tsuziku** [comment]
啊？setting.py没看过

**Comment by Tsuziku** [comment]
已经解决了，谢谢
