### ISSUE TITLE
Link play create room, Arcaea error: Could not connect to online server, all other features nominal

### ISSUE THREAD

**Issue by qwerfd2-wustl** [Lost-MSth/Arcaea-server#45]
Please let me know if more info is needed.

**Comment by Lost-MSth** [comment]
Many possible reasons.

First check your UDP port rules. Check the host of UDP via catching the packages.

**Comment by qwerfd2-wustl** [comment]
Is the UDP setting in Charles? Not sure.

The request to create a room is captured via Charles:

---
URL	http://172.27.100.174:8080/years/19/multiplayer/me/room/create
Status	Complete
Notes	Mapped from remote URL: https://arcapi-v2.lowiro.com/years/19/multiplayer/me/room/create
Response Code	200 OK
---

The in-game UI for link play briefly shows up before the error message.

**Comment by Lost-MSth** [comment]
Wait. Can you see the package context. The endpoint may be not right. Set it in the setting.py.

**Comment by qwerfd2-wustl** [comment]
Server returned success, here's the package content:

{
	"success": true,
	"value": {
		"endPoint": "172.27.100.174",
		"key": "3Ls8WGTV4tmz+9tms89ezQ==",
		"orderedAllowedSongs": "9393f3d39/d//3d/d3d3d/d3d3d3d/d3d3d3d3d3d3d3d3d393d3d3d3d3f3d3f3d3d3d3d/f3f3d3d3d3d3d/d3d3d3d3d3d393d3d3d3cPd3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3f3d3d3d/d3d3d3d3d3d3d3d3d3d3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		"playerId": "7817746",
		"port": 10900,
		"roomCode": "EJOW13",
		"roomId": "13401432862238994810",
		"token": "13401432862238994810",
		"userId": 2000001
	}
}

**Comment by qwerfd2-wustl** [comment]
I did not change the UDP port (10900), maybe I should? In that case, where should I look?

**Comment by Lost-MSth** [comment]
Endpoint/host wrong. Set it manually in setting please.

**Comment by qwerfd2-wustl** [comment]
Fixed, thank you :3
