### ISSUE TITLE
不知道能不能达到用户下歌时去请求其他网址的数据而不是从我本地下载

### ISSUE THREAD

**Issue by MizunaNako** [Lost-MSth/Arcaea-server#5]

**Comment by Lost-MSth** [comment]
你的意思是从官网下载？我觉得这不太好，首先是需要一个购买了许多歌的账号，然后还要顶着那可恶的网速下载，弄不好还可能封号
要是你需要从其他网站下载，可以把其他网站的数据下载到本地，当然可以是从官网（抓包得到url后浏览器直接请求是可以下载的，就是速度感人）

**Comment by MizunaNako** [comment]
不，我因为我是内网穿透，有流量限制，开私服让玩家下歌不现实，我朋友有一个有歌的服务器，我准备直接从那个网站下歌，然后不从我这获取歌曲数据

**Comment by Lost-MSth** [comment]
这太草了点吧（
这可能需要你单独改了，我怎么也想不到会有这种奇怪的需求
首先你朋友的服务器是怎么处理请求的？如果用的是我的，那有点小麻烦，毕竟我刚刚把下载token加上了，不能随便请求（需要去掉token验证）
当然如果你朋友那边可以随便请求下载，那就好多了，只需要改一点，arcdownload里面拼接url的那段(40~48行)，把token去掉并且url改成其它服务器的对应地址即可（但是这样也要求两个服务器的歌曲铺面数据是一样的）

**Comment by MizunaNako** [comment]
明白。谢谢您，开发server辛苦了
