### ISSUE TITLE
关于api接口

### ISSUE THREAD

**Issue by Decrabbityyy** [Lost-MSth/Arcaea-server#50]
/users、/songs、/user/me、/user/\<userid\>/best使用get方法不可用

**Comment by Decrabbityyy** [comment]
好像被吃掉尖括号了

**Comment by Lost-MSth** [comment]
至少/users接口可用，刚试了的，用的是setting里设置token的办法，如果你说单用户登录查询可能我权限管理还没写好吧

嘛，因为server模块在拆分重构，api也没有配套前端，所以没怎么关心api接口以及接口文档

**Comment by Lost-MSth** [comment]
等等，我回来看了这个，您说的该不会是GET请求无data导致服务器解析json错误吧
我的（） 93f4ad4999b8374aea13de434d82669e35807d7b
