### ISSUE TITLE
about download

### ISSUE THREAD

**Issue by Refute97** [Lost-MSth/Arcaea-server#51]
how to download all songs in 1 pack?, I can only download songs one by one in 1 pack..

**Comment by Lost-MSth** [comment]
Can you describe more details?

I haven't meet this and I guess it is due to the songlist file.

In the pack except free and extend pack, the songs will be downloaded at the same time, so what you said is unbelievable.

**Comment by Refute97** [comment]
![20220617_132109](https://user-images.githubusercontent.com/97284540/174237720-4a46f7e0-a3bc-4a95-a7d3-9961b7c01bfa.jpg)

my english is bad sorry.
as you can see in the picture i tried to download the songs in the BF package but not download them at the same time only 1 can i download..

**Comment by Lost-MSth** [comment]
Hmm so strange.
Does cmd have some messages? Or can you catch the package to see the context which the server send to the client?

**Comment by Refute97** [comment]
[17/Jun/2022 14:10:29] "GET /download/tempestissimo/base.ogg?t=f41971e5890ecbed12bfedefb6d71d68 HTTP/1.1" 200 -

[17/Jun/2022 14:10:33] "GET /latte/13/score/song/me?song_id=tempestissimo&difficulty=2&start=4&limit=18 HTTP/1.1" 200 -

Like this ?

**Comment by Refute97** [comment]
I got over it,
Thanks for the reply..
