### ISSUE TITLE
关于错误输出

### ISSUE THREAD

**Issue by Kongchenglige** [Lost-MSth/Arcaea-server#58]
似乎在出现错误的时候完全没有任何输出, 导致难以定位错误
如果有错误输出, 希望能告知如何开启
如果没有, 希望能够添加, 以免出现任何问题连个错误日志都无法提交.
谢谢
以及我刚刚看了下您写的wiki 您的config里开启更详细的错误日志也不会在控制台出现错误日志
log里边的错误日志是flask的 控制台的错误日志也是flask的
服务器内部错误并没有被输出
希望您能改进一下
谢谢

**Comment by Lost-MSth** [comment]
可以详细说明一下是哪个接口没有报错输出呢，我没记错的话，除了自定义异常外都会有输出

当然还有一种情况是服务器没有开始运行导致没有日志输出，也就是闪退了，那确实是个小问题，但其实只要用cmd就能看到报错信息，而且这种情况已经在q&a里说明了

**Comment by Kongchenglige** [comment]
您好, 我遇到的情况是返回200但实际返回的数据在内部处理时就已经被
raise NoData('The character of the user does not exist.')
而控制台并无任何提示

具体遇到的情况如下
在登录时请求 server/others.py 的 85 行 请求 /user/me
进入 core/user.py 的 453 行 return 语句
在return 时出现了错误
之后尝试修改进去一个 try expect 最终提示 错误具体信息为'The character of the user does not exist.'
在此期间控制台没有任何输出

**Comment by Lost-MSth** [comment]
啊这，这明显是我弄的自定义异常，所以不能算是服务器错误，但你说的对，对于没太多经验的人来说，定位错误有点困难，而且客户端没有那种特殊的错误提示

这个问题来自于切换全角色解锁开关导致的，嘛……很头疼的一个问题，user的属性中character相关属性共享了全解锁表user_char_full和普通表user_char，这个设计目前明显破坏了数据库数据完备性，若要解决，应该两种情况分开记录用户当前选择角色的信息
可是我懒，这涉及数据表变更，在增查改上也不是那么方便

所以目前没什么好想法，最好避免随意切换全解锁开关，后续可能会在全解锁开关变更后，强制将所有用户角色切到初始的0上

若有建议，非常欢迎

**Comment by Kongchenglige** [comment]
我仍建议您对自定义异常也在控制台输出具体错误.
就我而言, 我有其他语言的经验而并没有在python上的较深经验. 
定位此错误是在我一位Python经验丰富的朋友指导我花了整整一个小时定位的. 
真的不是什么好的经历. 
而且提示错误日志真的是一个必须功能, 您定义的一堆自定义异常都无法在控制台显示真的很要命

**Comment by Kongchenglige** [comment]
附加
您可以考虑在查询不到数据的时候返回默认的0并在控制台提示
用户2在登录时并不会出现问题
用户1也不会受到任何致命的影响
谢谢
