### ISSUE TITLE
同步存档疑似会自动上传存档的所有成绩到在线服务器

### ISSUE THREAD

**Issue by JoinChang** [Lost-MSth/Arcaea-server#6]
![-145268987ccd7bdf](https://user-images.githubusercontent.com/35451392/100546263-68881300-329b-11eb-85d5-77cd88174723.jpg)

如该图左下角的三个相同成绩，在其他曲目均相同。应该是上传本地存档到服务器导致的（不清楚）。

**Comment by Lost-MSth** [comment]
啊，看起来确实有点诡异
我想知道为啥是三个不同的用户，可以用后台查一下成绩吗
还有能确定是游戏内数据同步的问题吗

**Comment by Lost-MSth** [comment]
诶？等等，我有个想法，这三个账号该不会是一个人的吧
那就有可能，我同步数据的时候会把本地数据覆盖到服务器上，这是为了方便从官服向本地服同步数据，毕竟如果要重新打，有些成绩还是挺难重打出来的（我太菜了）
你的意思是像官服一样，本地数据和数据同步是独立的，与上传上去的成绩无关对吧，虽然不方便，但至少是能增加有人开小号快速刷榜的成本
啊这，我不太清楚如何选择，有好建议吗

**Comment by JoinChang** [comment]
确实是一个人的，我觉得同步的必要性应该不大。除了刷榜，而且还可以直接修改存档导致成绩的不真实（虽然上传也可以伪造

**Comment by Lost-MSth** [comment]
嗯，确实问题很多，我有个办法了，同步数据单独记录，但是给个后台能同步到best表的权限，这样就折中了
行，下次更新改掉（咕咕咕概率10%

（你怎么就透露了假成绩上传呢~arc这种游戏是防不住的，哎

**Comment by JoinChang** [comment]
顺便希望做个开关控制全角色或者全曲（

**Comment by Lost-MSth** [comment]
全曲我写了，不过出了点错，url写错了
全角色是啥意思？在全角色和两个初始角色之间切换吗？听起来挺奇怪的

**Comment by JoinChang** [comment]
后台设置的角色全开，我这边想把角色都全部解锁了

**Comment by Lost-MSth** [comment]
呃？我还是没明白
你是说想手动在游戏里解锁？这要大改啊，我世界模式写的时候没有处理奖励，购买系统也不包含角色，所以实际上解锁角色的功能根本没有(毕竟一开始就直接做成了全角色)

**Comment by JoinChang** [comment]
没，就是后台的aggregate返回全部角色

**Comment by Lost-MSth** [comment]
嗯？后台aggregate返回的不是全部角色吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JoinChang"<notifications@github.com&gt;; 
发送时间: 2020年12月1日(星期二) 晚上11:09
收件人: "Lost-MSth/Arcaea-server"<Arcaea-server@noreply.github.com&gt;; 
抄送: "TH"<th84292@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Lost-MSth/Arcaea-server] 同步存档疑似会自动上传存档的所有成绩到在线服务器 (#6)





 
没，就是后台的aggregate返回全部角色

**Comment by chinosk114514** [comment]
三个都是我的(

**Comment by JoinChang** [comment]
不是只有光和对立吗（
![Screenshot_20201203-094443_Arceae](https://user-images.githubusercontent.com/35451392/100952815-32bd8580-354c-11eb-851f-534fbd29fc3a.jpg)

**Comment by Lost-MSth** [comment]
啥？我傻了(
不是啊，是永远的全角色
等一下，你是不是碰上了新bug？是不是从以前的数据库同步更新过来的？后台的数据同步这部分我刚改过(优化，以应对表结构不同的情况)，bug什么的确实有可能
如果你会的话用sqlite之类的软件去查一下用户角色表(user_char)，八成是空表了

可能的解决方案: 在后台里面的角色修改底下刷新一下用户拥有角色表
