### ISSUE TITLE
Some BYD downloads don't work

### ISSUE THREAD

**Issue by rixtox** [Lost-MSth/Arcaea-server#60]
Using 47f05cdf1e8d28fb6d870ba4cb86382f98d5d110 server with v4.0.255 client.

Songs like Bookmaker, Dement, Fairytale, Goodtek, Infinity Heaven and more.

So I put `3.aff` for each song to their song ID folder properly. When downloading the song from client, I saw network requests for both `base.ogg`, `0.aff`, `1.aff`, `2.aff`, and `3.aff`. But after that only PST, PRS, FTR are available but not BYD. Checking the dl container folder also show only the base ogg and 0-2 aff, not showing the BYD aff file.

**Comment by Lost-MSth** [comment]
Wait... songs in free packs...
Only the byd charts of those songs can be downloaded. You just need a `3.aff` file in each song folder.
You said they cannot be downloaded. Maybe you changed the files after the server running or the folder names were wrong.
Emmm... Another possible reason is that you use the `iOS` device, so the download procedure must be in `https` connections.

**Comment by rixtox** [comment]
So I tried your suggestion, here is the server side folder structure:

```
└── database
   └── songs
      └── goodtek
         └── 3.aff
```

As you suggested, only the 3.aff file was in the goodtek directory.

And here are the network requests after clicking the download button for Goodtek BYD:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/2001277/179411541-e98153ef-6942-4523-93c2-741bdc359d37.png">

As expected, only the 3.aff file was downloaded. The connection was indeed in HTTPS as I provided the URL base in settings.py. The content of that network request was also fine. However, after that, the download button on the Goodtek BYD chart was still available, and checking the `dl` folder on the device shows no sign of a `goodtek_3` file:

```
iPad> cd dl && ls goodtek*
zsh: no matches found: goodtek*
```

**Comment by Lost-MSth** [comment]
WTF? It may be a new problem that haven't met before.
Well, I tried downloading it on the Android device. It is obviously ok.

It seems that the client received the file but didn't accept it. In the past, I will guess the ssl certification is not believable or the hash of the file is wrong. However you checked them carfully. Thus now I have no idea.

The best way is to get the packages from the official server and to see what I missed. I will try it later.

**Comment by rixtox** [comment]
Note that manually putting the BYD aff file to the device's dl folder then restart the app would work, but still, the server serving file can't be installed on the device.

**Comment by Lost-MSth** [comment]
Well I checked everything and only found a strange difference. I will try it later and I hope you can help me to verify my conjecture because of my lacking in iOS devices.

Sorry for handling the problem slowly. I am not on the holidays and so busy.

**Comment by rixtox** [comment]
It's alright. Sure I can help with any iOS releated testing etc.

**Comment by Lost-MSth** [comment]
Firstly, can you try to add a parameter in line 63 of `main.py`? 
```
return send_from_directory(Constant.SONG_FILE_FOLDER_PATH, file_path, as_attachment=True, conditional=True)
```

**Comment by rixtox** [comment]
OK I think I figured out... maybe...
So it seems no code needs to be changed... And yes we need to have only the 3.aff file in the songID folder, which is a hard requirement.

Then, since I used to have other files in the folder, when I tried to download, those files got downloaded and written to the dl folder (e.g. goodtek, goodtek_0, goodtek_1, goodtek_2 but not goodtek_3). At this point, no matter how I change the server side, the client won't write goodtek_3 even if it has a network request for it. What need to be done is to manually delete all the downloaded files for that song from the dl folder, restart app, and redownload.

I'm wondering if it's possible to specialize these songs so the server side only serves the 3.aff file regardless the existence of other files from the song folder. Since for completeness I have all the level files stored and put into the songs folder. It would be kind of troublesome to just maintain a folder structure for the Arcaea server.

**Comment by Lost-MSth** [comment]
Well, are you sure whether only the songs with byd charts in the base(free) pack have this problem? Does anything else work?

I am troubled about choosing which way to specify these songs.

**Comment by rixtox** [comment]
OK. I figured out the rule here. If `remote_dl` is `true`, then serve everything including 3.aff and 3.ogg if exists.

```
// example
    "dropdead": {
      "audio": {
        "3": {
          "checksum": "ae8dce75832b652b83989792d1b33f26",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_dropdead/3.ogg"
        },
        "checksum": "80255b334f118a8b758df76a929e3a99",
        "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_dropdead/base.ogg"
      },
      "chart": {
        "0": {
          "checksum": "ade5c0c8aa37e6786d9a605dc578e2a7",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_dropdead/0.aff"
        },
        "1": {
          "checksum": "75fe739cfd526af8b957ce7c03d50d43",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_dropdead/1.aff"
        },
        "2": {
          "checksum": "794829f11947c4b959b330719d3516ab",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_dropdead/2.aff"
        },
        "3": {
          "checksum": "846f7829546b6e44047229a2faab25c0",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_dropdead/3.aff"
        }
      }
    },
```

If `remote_dl` is not `true`, then only serve 3.aff and 3.ogg if exists.

```
// example
    "ignotus": {
      "chart": {
        "3": {
          "checksum": "2e88a286fd05354ccffe344aadc9c00f",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_ignotus/3.aff"
        }
      },
      "audio": {
        "3": {
          "checksum": "58c1503cc9a6b24b8e50bffff2908ceb",
          "url": "https://static-lb.lowiro.com/download/res/4.0.255/dl_ignotus/3.ogg"
        }
      }
    },
```
