### ISSUE TITLE
How to use this on android?

### ISSUE THREAD

**Issue by guranu** [Lost-MSth/Arcaea-server#64]
This is more of a question rather than anything but how do you use this on android?????

**Comment by Lost-MSth** [comment]
you mean `termux`?

**Comment by guranu** [comment]
Yes.

**Comment by guranu** [comment]
I hope you aren't going to say that i need root.

**Comment by Lost-MSth** [comment]
I think you don't need to root your device.

However, I do not suggest you to use `termux` to run the server and I haven't done any test so I am not sure whether it can work correctly.

**Comment by guranu** [comment]
Uh hello?

**Comment by guranu** [comment]
Well how about you test it then.

**Comment by guranu** [comment]
You said it yourself in the rquirements section of the code that it works with android
![Screenshot_20220730-075535_1](https://user-images.githubusercontent.com/103632948/181875324-8af24f88-7ebf-4fa9-af97-2638893fee17.jpg)

**Comment by Lost-MSth** [comment]
Theoretically it works and someone told me that he successed in building the server on Android. Thus I assume it's ok.

Obviously the main part of the server can run correctly. What I am worried about is whether the multiprocessing part and the udp server work regularly.

**Comment by guranu** [comment]
Oh ok anyways does this work with playstore version of arcaea? Or was this ment only for the chinese version of the game?

**Comment by Lost-MSth** [comment]
Well, it is just a server. The client can be anything, including different versions of `arcaea`.

**Comment by guranu** [comment]
Can you at least tell me how to use this on linux?

**Comment by Lost-MSth** [comment]
That's easy. Clone it from `github`, do some changes to `setting.py` and then run it.

Show me what I did: 
```shell
git clone https://github.com/Lost-MSth/Arcaea-server
cd Arcaea-server/
cd latest\ version/
pip3 install -r requirements.txt
python3 -B main.py
```
Well, using either `pip`/`python` or `pip3`/`python3` is depending on your environment.

Additionally, to change the setting file you can use:
```shell
vim setting.py
```

**Comment by guranu** [comment]
Does this work if i use celluar data?

**Comment by Lost-MSth** [comment]
It just need that the client can connect to the server. If your server and client is the same device, either WiFi or 4G is ok. (Maybe no network also works.)

**Comment by Young-Lord** [comment]
> Theoretically it works and someone told me that he successed in building the server on Android. Thus I assume it's ok.
> 
> Obviously the main part of the server can run correctly. What I am worried about is whether the multiprocessing part and the udp server work regularly.

Running on Termux is totally ok. [The bug of udp server](https://github.com/Lost-MSth/Arcaea-server/issues/48) can be solved by Upgrading python.

**Comment by guranu** [comment]
Ok then theres no problem running it.

**Comment by guranu** [comment]
> That's easy. Clone it from `github`, do some changes to `setting.py` and then run it.
> 
> Show you what I did:
> 
> ```shell
> git clone https://github.com/Lost-MSth/Arcaea-server
> cd Arcaea-server/
> cd latest\ version/
> pip3 install -r requirements.txt
> python3 -B main.py
> ```
> 
> Well, using either `pip`/`python` or `pip3`/`python3` is depending on your environment.
> 
> Additionally, to change the setting file you can use:
> 
> ```shell
> vim setting.py
> ```

Dumb question but do i add the / in cd arcaea-server?

**Comment by guranu** [comment]
> 

Do you type it like cd v/2.9.1/?

**Comment by guranu** [comment]
> That's easy. Clone it from `github`, do some changes to `setting.py` and then run it.
> 
> Show you what I did:
> 
> ```shell
> git clone https://github.com/Lost-MSth/Arcaea-server
> cd Arcaea-server/
> cd latest\ version/
> pip3 install -r requirements.txt
> python3 -B main.py
> ```
> 
> Well, using either `pip`/`python` or `pip3`/`python3` is depending on your environment.
> 
> Additionally, to change the setting file you can use:
> 
> ```shell
> vim setting.py
> ```

how do you type cd latest/ version

Do you type it like cd v/ 2.9.1?

**Comment by Young-Lord** [comment]
> how do you type cd latest/ version
> 
> Do you type it like cd v\ 2.9.1/?

```
cd latest\ version/
```
type a `\`, not a `/`

**Comment by guranu** [comment]
Sorry to be rude but could you add support for 4.0.256?

**Comment by Lost-MSth** [comment]
Why you think it can not support for other versions of the client? 4.0.256 is similar to the 4.0.255.

**Comment by guranu** [comment]
Oh ok.

**Comment by guranu** [comment]
How do i edit the .py file with vim?

**Comment by Lost-MSth** [comment]
Well... It is a large and comprehensive question.

`Vim` is a text editor on Linux. There are a lot of courses on the Internet to help you master the skill. The best way is to search and try and try.

Of course, you can also choose other ways to edit the file.

**Comment by guranu** [comment]
Ok so the server runs but i don't know how to use it in arcaea.

**Comment by guranu** [comment]
Hello?

**Comment by Lost-MSth** [comment]
See other issues or discussions. Almost everything I want to say is in the wiki and the readme.

**Comment by guranu** [comment]
I couldn't find anything other than using it throug charles. but i don't have a pc to use it. So can you tell me what to do after i managed to get the server running?

**Comment by Young-Lord** [comment]
> 

Lots of extra modification to Arcaea is required, which need some private tools. You might need to see [ArcaeaModder](https://arcaeamemory.github.io/ArcaeaModder/ModdersIndex.html) for further information (or email them).
btw, here [is not the right place for discussing client](https://github.com/Lost-MSth/Arcaea-server/wiki/Q&A#:~:text=It%20is%20important%20to%20say%20that%20it%20is%20a%20server%2C%20please%20don%27t%20ask%20about%20the%20cracked%20client.).
