### ISSUE TITLE
implement a server on android for 3.6+

### ISSUE THREAD

**Issue by Refute97** [Lost-MSth/Arcaea-server#65]
is it possible to implement a server on android for version 3.6+?
see the requirements such as doing remote mapping in that version, is it possible to do it on android?

**Comment by Lost-MSth** [comment]
Hmmm... The server is not the client. Version 3.6+ is the client version. You can surely run different versions of the server on the platform like Android.

Doing remote mapping is a way to make the connection between the server and the client. That's not the only method you can apply. It's optional.

**Comment by Refute97** [comment]
for version 3.6+ requires api mapping right?, to run server on android it runs fine, but after that how to apply it to game.. 
I think it should need remote mapping to connect to client and i ask how to do remote mapping on android?

**Comment by Lost-MSth** [comment]
I haven't tried the mapping remote on Android. 
Ask other people and wish you luck.
