### ISSUE TITLE
PTT计算没有EX保护机制

### ISSUE THREAD

**Issue by OasisAkari** [Lost-MSth/Arcaea-server#7]
1551
![image](https://user-images.githubusercontent.com/31803608/100761234-a2891e80-342d-11eb-88f8-3340b5719159.png)

**Comment by Lost-MSth** [comment]
啊这，recent的详细计算规则我不太确定，所以没加ex保护和hard tracklost保护
主要是arcaea3.0更新recent规则的时候我似乎遇到过ex掉分，所以很怀疑
arcwiki上的那个规则我看了，能确保它是对的的话我下次就改改
（要是能黑掉616服务器进去拿份源码就好了（不是）
