### ISSUE TITLE
A question about using the API

### ISSUE THREAD

**Issue by LangoABYSS** [Lost-MSth/Arcaea-server#70]
Hello, I'm using the API in the Arcara-server. I want you use the songs and the users to get the song list and best 30. However, I always receive 400 error. Do you have some suggestions or some examples for using these APIs? Thanks very much!

**Comment by Lost-MSth** [comment]
Hmmm, can you see the error message from the server? I guess it is "Payload must be a valid json".
Well, I want to more details. And if you use a fontpage to connect the API, I can give you an example.

**Comment by LangoABYSS** [comment]
> Hmmm, can you see the error message from the server? I guess it is "Payload must be a valid json". Well, I want to more details. And if you use a frontend webpage to connect the API, I can give you an example.

Yes. It's "Payload must be a valid json". And I don't know how it be raised. I'm just calling the API by an Arcbot. Here is my code for calling this.
`best_30_list, statu = api.users.users_user_b30_get(player_id, player_id)`
Do you have the examples for this situation? Or was I transport the wrong arguments? The play_id is a string.

**Comment by Lost-MSth** [comment]
Well, Arcbot or anything else don't match the API of this repo. They may use botarcapi or even official API. That's different.
If you want to use them, you should change some codes. Otherwise build your own bot.

For example, send a `POST` request to `http://IP:PORT/api/v1/users/USER_ID/b30` and then you can get the best30 json data.

**Comment by LangoABYSS** [comment]
> Well, Arcbot or anything else don't match the API of this repo. They may use botarcapi or even official API. That's different. If you want to use them, you should change some codes. Otherwise build your own bot.
> 
> For example, send a `GET` request to `http://IP:PORT/api/v1/users/USER_ID/b30` and then you can get the best30 json data.

I think I have known your meaning. Thanks very much! By the way, is the USER_ID a UID or User code?

**Comment by LangoABYSS** [comment]
> 



> `user_id` is autoincrement and it's type is `int`. `user_code` is 9-digit random number and it's type is `str`.
> 
> You can post to the `api/v1/token` endpoint to login(`{'auth': base64('<user_id>:<password>')}`). Or just set a token string in the config file (It has a highest role/power.).
> 
> However the api part is still in building with frontend and may have some changes in the future. The best way to use it at present is to read the code in `api` folder.

Thanks very much. So how should I change the code line with token? `url = requests.get("http://IP:PORT/api/v1/users/USER_ID/b30")` and with a header?

**Comment by Lost-MSth** [comment]
Yes. I get it use `request.headers['Token']`.

**Comment by LangoABYSS** [comment]
> Yes. I get it use `request.headers['Token']`.

OK. And does it means I should transfer the user_code provided by the players to their user_id since they may not get access to their use_id?

**Comment by Lost-MSth** [comment]
They can get their `user_id`. But the client will not show it so they may not know that.
Maybe an extra search is needed to get the `user_id` if a `name` or `user_code` is provided.

**Comment by LangoABYSS** [comment]
> They can get their `user_id`. But the client will not show it so they may not know that. Maybe an extra search is needed to get the `user_id` if a `name` or `user_code` is provided.

Does this search provided by API?

**Comment by Lost-MSth** [comment]
Emmm.... Yes, but it is not very good for database performance. Maybe not very quick.
`GET` request of `/api/v1/users?query={base64 json data}` or just put json data in request body. 
Data like `{'query': {'name': 'admin'}}` means searching by exact name.

**Comment by Lost-MSth** [comment]
Strange. I can get the data via it.
```python
def func()
    headers = {'Token': '123'}
    r = requests.get( 'http://*.*.*.*/api/v1/users/******/b30', headers=headers)
    print(r.status_code)
    print(r.text)
```

**Comment by LangoABYSS** [comment]
> Strange. I can get the data via it.
> 
> ```python
> def func()
>     headers = {'Token': '123'}
>     r = requests.get( 'http://*.*.*.*/api/v1/users/******/b30', headers=headers)
>     print(r.status_code)
>     print(r.text)
> ```

OK. I've solve the problems. Thanks for your patient. Then I met with another quesiton about query:
`res = requests.get(url = "http://x.x.x.x:x/api/v1/users?query={'query': {'name': user_name}}", headers = headers)`
I always receive the information about the admin. Is there any wrong in this code? Thanks for your helping!

**Comment by Lost-MSth** [comment]
Emmmm  The query param should be encoded to base64. 

(Use this because GET request cannot have data standardly. The problem is open to a better method if you have one.)

**Comment by LangoABYSS** [comment]
> Emmmm The query param should be encoded to base64.
> 
> (Use this because GET request cannot have data standardly. The problem is open to a better method if you have one.)

OK! Maybe the last question. When I request for b30, sometimes I get -999 Unknown Error. This may happen on some of the user_ID, but this work well on others. How this Unknown Error raised?

And by the way, thanks for your patience!!

**Comment by Lost-MSth** [comment]
Oh I believe that is a bug? Maybe there are no data of these users. You can see the message in console/CMD and check what happened.

**Comment by LangoABYSS** [comment]
> Oh I believe that is a bug? Maybe there are no data of these users. You can see the message in console/CMD and check what happened.

In the console, it just shows an unknown error for -999 code. I think there is data for them because I can search the UserID in the webpage.

**Comment by Lost-MSth** [comment]
Too strange. Is it a warning or an error? And the details of the message? (I mean the console of the server.)

In some past days, I fix a bug that no song name makes the b30 API break down.

**Comment by LangoABYSS** [comment]
> Too strange. Is it a warning or an error? And the details of the message? (I mean the console of the server.)
> 
> In some past days, I fix a bug that no song name makes the b30 API break down.

11-02 17:25:14 [DEBUG] nonebot | Running handler Dependent(call=get_best_30)
2000060
{'code': -999, 'data': {}, 'msg': 'Unknown Error'}
Here is the console output. The digit code is the userID I print on it, and there is no other warning or error. Then the progress broke down because I get nothing from the API.

**Comment by Lost-MSth** [comment]
Emmm...That's not what I meant. This is the console log of the client/bot. I want to see the console of the **server**.

**Comment by LangoABYSS** [comment]
> Emmm...That's not what I meant. This is the console log of the client/bot. I want to see the console of the **server**.

Ohh, I'm sorry for that. I check the server, and there is actually an error information:
[2022-11-02 17:41:08,901] ERROR in sql: ['Traceback (most recent call last):\n', '  File "C:\\Users\\Administrator\\Desktop\\v2.10.0\\v2.10.0\\api\\users.py", line 93, in users_user_b30_get\n    x.select_song_name()\n', '  File "C:\\Users\\Administrator\\Desktop\\v2.10.0\\v2.10.0\\core\\score.py", line 583, in select_song_name\n    score.song.song_name = self.c.fetchone()[0]\n', "TypeError: 'NoneType' object is not subscriptable\n"]
[2022-11-02 17:41:08,901] INFO in _internal: 81.68.78.91 - - [02/Nov/2022 17:41:08] "GET /api/v1/users/2000060/b30 HTTP/1.1" 200 -

**Comment by LangoABYSS** [comment]
> Emmm...That's not what I meant. This is the console log of the client/bot. I want to see the console of the **server**.

Maybe I know the question. Is it made by a deleted song?

**Comment by Lost-MSth** [comment]
Great. The problem is clear now. I have fixed this in the newest commit.
Or you just need to change some code.
In the bottom of `core/score.py`, the code should be `score.song.song_name = x[0] if x else ''`.

**Comment by LangoABYSS** [comment]
> score.song.song_name = x[0] if x else ''

def select_song_name(self) -> None:
        '''为所有成绩中的song_id查询song_name'''
        if self.scores is None:
            return
        for score in self.scores:
            self.c.execute(
                '''select name from chart where song_id = ?''', (score.song.song_id,))
            score.song.song_name = self.c.fetchone()[0]

Is it in here? Or maybe the last line?

**Comment by Lost-MSth** [comment]
Change the last line please.

https://github.com/Lost-MSth/Arcaea-server/blob/ba36190f304602e1eb72da2439d2767b0c3b6d39/latest%20version/core/score.py#L576-L584

**Comment by LangoABYSS** [comment]
I'm sorry to another question. Is there anything changes in the later version? Such as the url in the API. After upgrading to the later version, a 404 not found error raises when I use the origin link.

**Comment by LangoABYSS** [comment]
> Change the last line please.
> 
> https://github.com/Lost-MSth/Arcaea-server/blob/ba36190f304602e1eb72da2439d2767b0c3b6d39/latest%20version/core/score.py#L576-L584

I'm sorry to another question. Is there anything changes in the later version? Such as the url in the API. After upgrading to the later version, a 404 not found error raises when I use the origin link.

**Comment by Lost-MSth** [comment]
Emmmm... there are some changes but I think a 404 error is not because of them. Which api has this problem? I need more details.

**Comment by LangoABYSS** [comment]
> Emmmm... there are some changes but I think a 404 error is not because of them. Which api has this problem? I need more details.



> Emmmm... there are some changes but I think a 404 error is not because of them. Which api has this problem? I need more details.

`    headers = {"token": "xx"}
    que = json.dumps({'query': {'name': player_name}})
    res = requests.get(url = "http://x.x.x.x:x/api/v1/users?query=que", headers = headers)
    #print(res.text)
    res = res.json()`
I have not changed the code, and it suddenly raised 404 Not Found after upgrading. Would you mind check it?

**Comment by Lost-MSth** [comment]
Hmm? Do you really use these code? It is even wrong.

1. `que` is a json string, but we need a base64 string. So you should encode it.
2. In the url, the `que` is a constant string but not a variable. 
3. Is it possible for you to get a 404? The wrong query can only lead to a 500 error.

**Comment by LangoABYSS** [comment]
> Hmm? Do you really use these code? It is even wrong.
> 
> 1. `que` is a json string, but we need a base64 string. So you should encode it.
> 2. In the url, the `que` is a constant string but not a variable.
> 3. Is it possible for you to get a 404? The wrong query can only lead to a 500 error.

I used these code before and I can get the data. After upgrading, these code doesn't work anymore. I will try this.

**Comment by LangoABYSS** [comment]
> Hmm? Do you really use these code? It is even wrong.
> 
> 1. `que` is a json string, but we need a base64 string. So you should encode it.
> 2. In the url, the `que` is a constant string but not a variable.
> 3. Is it possible for you to get a 404? The wrong query can only lead to a 500 error.

Maybe is it like this:
`
    que = base64.b64encode(json.dumps({'query': {'name': player_name}}).encode())
    res = requests.get(url = f"http://81.68.78.91:817/api/v1/users?query={que}", headers = headers)
    print(res.text)
    res = res.json()
`
And I checked the output, actually it's -999 Unknown error. 404 Error is raised because I do not get the user_id for request the b30.

**Comment by Lost-MSth** [comment]
Oh, maybe a bug? You can enable the warning log in the config to see what happend. There will be an exception or a custom error.

**Comment by LangoABYSS** [comment]
> Oh, maybe a bug? You can enable the warning log in the config to see what happend. There will be an exception or a custom error.

`
[2022-11-12 20:14:20,105] ERROR in app: Exception on /api/v1/users [GET]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\Desktop\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\Desktop\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\Desktop\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\Desktop\v2.10.0 - 副本\v2.10.0\api\api_auth.py", line 45, in wrapped_view
    return view(user, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\v2.10.0 - 副本\v2.10.0\api\api_auth.py", line 71, in wrapped_view
    b64decode(request.args['query']).decode())
  File "C:\Users\Administrator\Desktop\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (49) cannot be 1 more than a multiple of 4
`
Here is the error log.

**Comment by Lost-MSth** [comment]
Obviously, it means the `query` param is not a valid base64 string. Check your code. You use bytes not string.

**Comment by LangoABYSS** [comment]
> Obviously, it means the `query` param is not a valid base64 string. Check your code. You use bytes not string.

Should I write like this:
`
    que = base64.b64encode(json.dumps({'query': {'name': player_name}}).encode('utf-8'))
    res = requests.get(url = f"http://x.x.x.x:x/api/v1/users?query={que}", headers = headers)
`
And you're right, I get 500 internal error after changing the code.

**Comment by Lost-MSth** [comment]
........
`que = base64.b64encode(json.dumps({'query': {'name': player_name}}).encode()).decode()`

**Comment by LangoABYSS** [comment]
> que = base64.b64encode(json.dumps({'query': {'name': player_name}}).encode()).decode()

OK. I'm sorry to bother you in the weekend. Really thanks for your patient!
