### ISSUE TITLE
4.0客户端如何绕过（或删除）SSL使客户端连接localhost

### ISSUE THREAD

**Issue by xingjiFIUG** [Lost-MSth/Arcaea-server#74]
请问如何使4.0客户端如何绕过（或删除）SSL使客户端连接localhost

我在ida中找了很久也试过了很多方法没没能绕过ssl去修改api

实在是没办法了，问了很多人都对这个一无所知QAQ

**Comment by Lost-MSth** [comment]
https://github.com/Lost-MSth/Arcaea-server/issues/64#issuecomment-1257205897
> 以及去看看discussions、issues

**Comment by xingjiFIUG** [comment]
> [#64 (comment)](https://github.com/Lost-MSth/Arcaea-server/issues/64#issuecomment-1257205897)
> 
> > 以及去看看discussions、issues
我明白了，我用中间人攻击办法就可以了，谢谢您
