### ISSUE TITLE
怎么在安卓端游戏登录啊

### ISSUE THREAD

**Issue by handsomepwy** [Lost-MSth/Arcaea-server#76]
**可以具体讲一下如何在安卓端连接服务器吗**
大佬你好，我在自己的Linux服务器端（Debian9）成功跑起来了，config.py几乎没做改动
在我的手机上，我并不清楚如何设置，所以我连接WiFi后在高级选项中设置手动代理，主机我设置了自己的域名（指向了服务器IP），端口设置的是我在config.py中设置的8080，之后我也尝试了10900和10901（LINK_PLAY的俩端口）。之后我在flask输出的日志中看到了访问baidu.com这类的日志，我的手机显示无法上网,，说明服务器访问成功了。
之后，我寻思没用户名和密码，于是我把服务器上的arcaea_database.db复制到本地，用一个查看器把user表加了一行（其它表没动过），基本与你给的恶臭的那一行差不多，用户名和密码自己填的。然后我把它替换了服务器上的数据库。
然后，我登录游戏，发现显示密码或用户名错误。
于是我在/web/login路由的修改密码中把密码修改了（查询用户查询得到），此时复制服务器上的数据库，发现user表我的密码看不懂（64个字符）。
然后，我又一次登录游戏，发现显示密码或用户名错误。

**附加内容**
大佬我觉得我们其实很“镜像”，你用的flask和sqlite3，我正好也只会一点点，当然了，你在这方面的研究比我深得多。
希望能尽快回复我吧，谢谢。

**Comment by handsomepwy** [comment]
奥对了config.py里面的/join/21的用处是啥，因为添加代理那里没有填路由的位置啊

**Comment by Lost-MSth** [comment]
请先对以下内容有所了解：
1. 这个项目是什么服务端
2. 什么是代理服务器，为什么要用WiFi代理，作用是什么
3. github issue、discussion、wiki分别有什么用

**Comment by handsomepwy** [comment]
既然这是一个用python写的repo，并且在Linux上运行成功，因此我认为只要不报错，均可
我用WiFi代理使手机发出的请求都由代理服务器接受，因此当我在arcaea中登录时，请求发送到了服务器，而不是那个网站，使代理服务器“骗”arcaea说登录成功并完成后续操作
GitHub issue可以提出bug/建议。。。好的大佬我错了
