### ISSUE TITLE
WARNING in main: TCP-172.31.128.1-No authentication, why no authentication?

### ISSUE THREAD

**Issue by enchanteddaemon** [Lost-MSth/Arcaea-server#79]
my friend hosted it

**Comment by Lost-MSth** [comment]
I am not sure what you mean.
The warning message shows that the linkplay server gets the wrong auth token.

**Comment by enchanteddaemon** [comment]
> I am not sure what you mean.
> The warning message shows that the linkplay server gets the wrong auth token. 

where do i get the auth for linkplay

**Comment by Lost-MSth** [comment]
The string `AUTHENTICATION` in `linkplay_server/config.py`.
It should be same with the string `LINKPLAY_AUTHENTICATION` in `config.py`.
