### ISSUE TITLE
服务端版本迭代后登录提示未知错误

### ISSUE THREAD

**Issue by JoinChang** [Lost-MSth/Arcaea-server#8]
更新操作为压缩包内文件覆盖到目录，在网页端上传旧数据库。客户端也更新了新的版本。
提示未知错误，但重新输入账号密码仍可正常登录（估计是 token 获取不到）

![70a84486b7840586](https://user-images.githubusercontent.com/35451392/101239982-0f026700-3727-11eb-998f-ff73526e2fda.jpg)

**Comment by Lost-MSth** [comment]
啊这，这我知道的（
就是数据迁移的时候token表不会去同步，会需要重新登录
emm我觉得不是大事，要是觉得重新登录很麻烦我可以改一下（但事实上，arcaea更新的时候要重新登录的吧）

**Comment by JoinChang** [comment]
arc更新的时候token也不会掉的（

**Comment by Lost-MSth** [comment]
草（）
我每次都是删了重新下的哈哈哈（不然签名不一致（我改包了））
那好，我改一下
