### ISSUE TITLE
Why my server keeps forwarding request to official server

### ISSUE THREAD

**Issue by gianghomang** [Lost-MSth/Arcaea-server#80]
I have connected to my prv server but when i log in my main account it still have progress on official server

**Comment by gianghomang** [comment]
Sorry for bad english 😞

**Comment by Lost-MSth** [comment]
Show me more details. Which way did you use to link to local server? Did you see any messages in server's console?

**Comment by gianghomang** [comment]
I'm using proxy
![Uploading Screenshot_2022-12-13-20-46-28-57_41a74ddf68be21faad2fbbb691b15143.jpg…]()

**Comment by gianghomang** [comment]
I'm using proxy
![Screenshot_2022-12-13-20-46-28-57_41a74ddf68be21faad2fbbb691b15143](https://user-images.githubusercontent.com/83568006/207353690-1b7fe188-0729-442e-917e-46c1522814ff.jpg)

**Comment by gianghomang** [comment]
The first line is host name and second line is port

**Comment by gianghomang** [comment]
here is my console window
![image](https://user-images.githubusercontent.com/83568006/207354876-3401149a-6009-4c4d-a4b1-8ae3961f7d64.png)

**Comment by gianghomang** [comment]
![Screenshot_2022-12-13-21-09-05-87_3de306e3178de90c8b13f9c4ddd4419a](https://user-images.githubusercontent.com/83568006/207355769-f63c3a76-7a14-41ba-b0cf-758ff0012714.jpg)
Have tried to login but it still have progression save as lowiro server

**Comment by Lost-MSth** [comment]
OK. I think you misunderstood this repo. It is a game server not a proxy server. If you want to use proxy you need another application.

**Comment by gianghomang** [comment]
I don't know how to connect to my server 😢

**Comment by Lost-MSth** [comment]
Well, there are many ways to realize this. You can look at the issues and discussions to get some ideas.
Additionally, this repo cannot help you in this respect. See https://github.com/Lost-MSth/Arcaea-server/issues/64#issuecomment-1257205897.
