### ISSUE TITLE
API score ranklist for a song

### ISSUE THREAD

**Issue by CrystalMystique** [Lost-MSth/Arcaea-server#81]
Hello, I want to get the score ranking list of a single song, can this be done by using the API /songs or /scores?

Thanks very much!

**Comment by Lost-MSth** [comment]
At present, the answer is no.
Sorry for that, but this is a good feature. I will add it in several days.

**Comment by CrystalMystique** [comment]
> At present, the answer is no. Sorry for that, but this is a good feature. I will add it in several days.

Okay. I see about this. And another problem, I think there is something wrong on /users/r30, I've played some new songs, and it does not be found in r30 list.

**Comment by Lost-MSth** [comment]
> Okay. I see about this. And another problem, I think there is something wrong on /users/r30, I've played some new songs, and it does not be found in r30 list. Does it caused by network?

Can you confirm that those songs are ranked? If a song doesn't exist in the database or has a chart const below zero, the score of this song will be unranked and not be included in the recent30.

**Comment by CrystalMystique** [comment]
> > Okay. I see about this. And another problem, I think there is something wrong on /users/r30, I've played some new songs, and it does not be found in r30 list. Does it caused by network?
> 
> Can you confirm that those songs are ranked? If a song doesn't exist in the database or has a chart const below zero, the score of this song will be unranked and not be included in the recent30.

I think they are ranked. I've played a song twice, and it is included into r30 list at the second time.

**Comment by CrystalMystique** [comment]
> > > Okay. I see about this. And another problem, I think there is something wrong on /users/r30, I've played some new songs, and it does not be found in r30 list. Does it caused by network?
> > 
> > 
> > Can you confirm that those songs are ranked? If a song doesn't exist in the database or has a chart const below zero, the score of this song will be unranked and not be included in the recent30.
> 
> I think they are ranked. I've played a song twice, and it is included into r30 list at the second time. And I can see this song in the b30 list and do dot see this in r30 list

**Comment by Lost-MSth** [comment]
> I think they are ranked. I've played a song twice, and it is included into r30 list at the second time.

That's so strange. Oh wait, you said 'new songs', but you didn't mean it is a new account right?
Obviously, adding the scores of these new songs into the recent30 will make your r10 ptt down. And the first play of one song will be protected, just like EX protection. (Of course I am not sure whether the official server has this protection or not.)

**Comment by CrystalMystique** [comment]
hmmm. I know what's your mean. So is there any approach to get the song latest played such as r10? For example, the latest 10 songs played.

**Comment by Lost-MSth** [comment]
> hmmm. I know what's your mean. So is there any approach to get the song latest played such as r10? For example, the latest 10 songs played.

Well. It is impossible at present. Only one lastest played score will be recorded. Other scores are redundant.

Emmmm... In next version, the log database will be added and all playing histories will be recorded. However the cost is the database file will be very large and can be unlimitedly expanding. I have no idea how to use it. Anyhow you can get the latest played 10 scores in that version.

**Comment by CrystalMystique** [comment]
> 

Maybe I think that's Okay, and how can I get the one lastest played score?

**Comment by Lost-MSth** [comment]
> Maybe I think that's Okay, and how can I get the one lastest played score? I think I've not see that in the API document.

`recent_score` in the response of `/<user_id> GET`
https://github.com/Lost-MSth/Arcaea-server/wiki/API-users#get-1

It is the same as the game's `/user/me`. So the recent score will be included, which is used in friend list.
