### ISSUE TITLE
为什么我打开run.bat会闪退

### ISSUE THREAD

**Issue by 5555-cl** [Lost-MSth/Arcaea-server#82]
打开run.bat闪一下没了

**Comment by Lost-MSth** [comment]
https://github.com/Lost-MSth/Arcaea-server/wiki/Q&A#error-when-starting-the-server-启动服务端时出现问题
实际上有报错，只是一闪而过了，用CMD运行可以看到信息

**Comment by RnJ4** [comment]
可以在run.bat的最后一行加一个pause方便看报错

**Comment by 5555-cl** [comment]
![QQ截图20221220130605](https://user-images.githubusercontent.com/68059470/208588189-5ab72e53-54cc-475e-bdb0-33e86db6ce83.png)
啥也没显示咋办

**Comment by 5555-cl** [comment]
是的

**Comment by Lost-MSth** [comment]
直接用CMD运行，或者直接对`main.py`用IDLE打开后`F5`运行

**Comment by 5555-cl** [comment]
![QQ截图20221220131954](https://user-images.githubusercontent.com/68059470/208589687-ca20ce19-8175-4ab9-af40-3347d3122636.png)

**Comment by Lost-MSth** [comment]
https://github.com/Lost-MSth/Arcaea-server/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#python模块

**Comment by 5555-cl** [comment]
现在开始报错了

**Comment by Young-Lord** [comment]
pip install limits
