### ISSUE TITLE
 请把readme里的两个下载站删了，它们停止运营了

### ISSUE THREAD

**Issue by winload771** [Lost-MSth/Arcaea-server#83]
**What you want to know 你想知道什么**
Clearly describe your question here.

Please delete lowi.ro&rhydown.com in readme.
Because lowi.ro&rhydown.com Download Station was stopped work.
请把readme里的两个下载站删了，它们停止运营了

**Additional context 附加内容**
Add anything other here. Your abilities or knowledge base, your contact information, some pictures...

**Comment by Lost-MSth** [comment]
是的，我知道（
等几天一起更新
