### ISSUE TITLE
客户端闪退

### ISSUE THREAD

**Issue by NFHr** [Lost-MSth/Arcaea-server#85]
**What you want to know 你想知道什么**
成功连接至服务器，但是在进入开始游戏后会闪退，想知道这种情况是什么导致的。

**Additional context 附加内容**
客户端的songlist和packlist已修改

**Comment by Lost-MSth** [comment]
连接服务器后闪退，可能是idx硬编码，或者双端数据不匹配
离线状态闪退可能性就太多了（）

**Comment by NFHr** [comment]
已发现是idx硬编码问题，谢谢！
但是现在会结算闪退.....

**Comment by Lost-MSth** [comment]
联网状态下结算闪退是吗，有人遇到过，似乎是客户端问题（服务端没有收到请求则必是客户端问题），原因不明（我怀疑是异象或者finale什么的）

**Comment by NFHr** [comment]
是的，服务端没有收到请求。另外尝试替换了原版的songs文件夹，没有出现结算闪退，大概是slst的问题吧

**Comment by NFHr** [comment]
从别的私服改了一份slst，已解决。
