### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by enchanteddaemon** [Lost-MSth/Arcaea-server#87]
![Screenshot_2023-01-10-23-43-18-71_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/100534753/211597101-e53780eb-773e-4969-8f74-a5d889dbefbb.jpg)

**Comment by Lost-MSth** [comment]
Link Play authentication failed.
Please make sure that the token in `linkplay_server/config.py` is the same with that in `config.py`.

**Comment by enchanteddaemon** [comment]
> Link Play authentication failed.
> Please make sure that the token in `linkplay_server/config.py` is the same with that in `config.py`.

it is the same, i still get warning

**Comment by Lost-MSth** [comment]
Really? Hmmm maybe you need to uncomment line 135 in `linkplay_server/main.py` to see the data from the main server.

**Comment by enchanteddaemon** [comment]
> Really? Hmmm maybe you need to uncomment line 135 in `linkplay_server/main.py` to see the data from the main server.

![Screenshot_2023-01-13-21-34-45-45_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/100534753/212332338-e55af7ec-40be-4955-952f-0398bcb092cd.jpg)![Screenshot_2023-01-13-21-34-56-00_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/100534753/212332358-0b3db3b0-b92f-4465-896e-d5662e0a7c38.jpg)
