### ISSUE TITLE
部分新注册账号无法正常结算

### ISSUE THREAD

**Issue by JoinChang** [Lost-MSth/Arcaea-server#9]
曲目在服务器有记录，官方端也一样

![-7d12c929dc308b5e](https://user-images.githubusercontent.com/35451392/102849065-43796100-4451-11eb-83d5-53f2bdd45c4f.jpg)

**Comment by Lost-MSth** [comment]
确实，我知道了（wssb
是因为ex保护，ex保护计算了recent30总rating，但新账户的r30的数据是None，所以出错了
已经push了，可以对比着改一下（注意数据保存）

**Comment by JoinChang** [comment]
ex保护是不是没生效

**Comment by Lost-MSth** [comment]
emm出现了这样的情况吗？
我没太检查，最近一直在玩，ex的时候确实没掉过也就没管()
