### ISSUE TITLE
Code 400: HTTP Status BAD REQUEST

### ISSUE THREAD

**Issue by Snoflwr** [Lost-MSth/Arcaea-server#96]
我在笔记本上运行了 server，然后将 iPad 连接到笔记本的移动热点，通过 Charles 的 Map Remote 功能将域名 arcapi-v2.lowiro.com 映射到了笔记本的 iPv4 地址；客户端已去除了 Hash 校验，解锁了 Beyond 与 Scenecontrol 等相关功能；服务端能够对客户端的登录做出响应。

但是服务端的响应显示客户端 Request 的请求格式不正确 T_T

![1](https://user-images.githubusercontent.com/95011950/223045768-72a788a8-8e02-487c-a4a1-626ee6933d1e.png)

**Comment by Lost-MSth** [comment]
将提示扔进百度里就知道问题了，服务端开的是http不要用https

**Comment by Snoflwr** [comment]
客户端的请求是 HTTP:

![2](https://user-images.githubusercontent.com/95011950/223048222-af2613cf-06ff-43e8-84a1-7037c61d5691.png)

服务端也默认了 HTTP：

![3](https://user-images.githubusercontent.com/95011950/223048121-96758baa-178d-4caf-b09f-543cd3197272.png)

不知道是不是这样 QAQ

**Comment by Lost-MSth** [comment]
客户端发送的请求是HTTP？确定吗？客户端版本号多少

**Comment by Snoflwr** [comment]
<html>
<body>


  | POST /latte/13/auth/login HTTP/1.1
-- | --
Host | tqlwsl.moe:61616
Accept | */*
Authorization | Basic YWRtaW46YWRtaW4=
AppVersion | 3.5.3%2F20210410%2Frelease
Accept-Language | zh-cn
Cache-Control | no-cache
Accept-Encoding | gzip, deflate, br
Content-Type | application/x-www-form-urlencoded; charset=utf-8
DeviceId | 5C32E939-475A-4491-9D2C-D19BEBCF0D8B
User-Agent | Arc-mobile/3.5.3.4 CFNetwork/1335.0.3 Darwin/21.6.0
Content-Length | 29
Connection | keep-alive


</body>
</html>

**Comment by Snoflwr** [comment]
<html>
<body>


  | POST /latte/13/auth/login HTTP/1.1
-- | --
Host | tqlwsl.moe:61616
Accept | */*
Authorization | Basic YWRtaW46YWRtaW4=
AppVersion | 3.5.3%2F20210410%2Frelease
Accept-Language | zh-cn
Cache-Control | no-cache
Accept-Encoding | gzip, deflate, br
Content-Type | application/x-www-form-urlencoded; charset=utf-8
DeviceId | 5C32E939-475A-4491-9D2C-D19BEBCF0D8B
User-Agent | Arc-mobile/3.5.3.4 CFNetwork/1335.0.3 Darwin/21.6.0
Content-Length | 29
Connection | keep-alive


</body>
</html>

**Comment by Snoflwr** [comment]
想玩最新版本/
但是在 IDA 琢磨好久也没能解决双向验证 只能找远古版本/叹气

**Comment by Lost-MSth** [comment]
3.5.3？直接改二进制里 API 地址不就好了
而且我猜这个是 https 请求

**Comment by Snoflwr** [comment]
看错了确实是https 谢谢大佬指点
话说 api 这样改完就行了嘛/

![4](https://user-images.githubusercontent.com/95011950/223063386-9060c793-a560-4551-b207-d669b101bdfc.png)

**Comment by Lost-MSth** [comment]
应该可以，试试就知道了（）

**Comment by Snoflwr** [comment]
![6](https://user-images.githubusercontent.com/95011950/223069561-393b06fd-363c-461b-bc7b-a388d9b6ffe7.png)

![5](https://user-images.githubusercontent.com/95011950/223069167-ab2fa08c-c703-42ac-a33d-ff2df243033b.png)

坏了 甚至发不出包了/哭哭

**Comment by Lost-MSth** [comment]
服务端没反应？那就是改错了（检查十六进制，别看汇编，长度不能超，末尾可以补00

**Comment by Snoflwr** [comment]
检查过了就是这样 是因为没有域名不可以吗（）
api改成baidu什么的 服务端至少能收到请求

**Comment by Lost-MSth** [comment]
跟域名有什么关系（）

ip 是内网的服务端 ip 吗，端口正确吗？最简单的验证办法就是手机浏览器看一下

**Comment by Snoflwr** [comment]
手机浏览器是可以看到hello world的

**Comment by Snoflwr** [comment]
感谢大佬！经过一下午的努力终于成功了ww

**Comment by Snoflwr** [comment]
远古版本玩的很开心（。~~如果能教教4.3的新版本怎样与服务器建立连接就更好了~~
