### ISSUE TITLE
arcsong.db 相关 docs 过时

### ISSUE THREAD

**Issue by Young-Lord** [Lost-MSth/Arcaea-server#98]
现在的`arcaea_database.db`中使用`chart`表存储铺面信息，故[`update_song.py`](https://github.com/Lost-MSth/Arcaea-server/blob/master/tools/update_song.py)无法正确导入谱面数据

**Comment by Lost-MSth** [comment]
挠头，数据库来源是 [arcsong.db](https://github.com/Arcaea-Infinity/ArcaeaSongDatabase) 吗？
三个文件丢一起跑脚本就行，并没有发现什么问题，来点错误信息 / 复现过程

**Comment by Young-Lord** [comment]
不好意思，我的问题xxx
arcsong.db 貌似用了某一个错的 可以close了
